#!/bin/sh
# Sweep SSF through every meaningful crypto-config permutation and confirm each
# builds clean and passes the unit suite. Catches regressions where a config
# only the auto-derivation reaches becomes broken (e.g. a header-gating bug in
# a flag-conditional code path).
#
# Configs covered (8 total):
#   1. default                            (all 5 flags on)
#   2. pure ECC, both curves              (RSA all off)
#   3. ECC P-256 only                     (P-384 off, RSA all off)
#   4. ECC P-384 only                     (P-256 off, RSA all off)
#   5. RSA-2048 + both curves
#   6. RSA-3072 + both curves
#   7. RSA-4096 + both curves
#   8. embedded-min: RSA-2048 + P-256
#
# The auto-derived SSF_BN_CONFIG_MAX_BITS varies (768 / 512 / 4096 / 6144 /
# 8192) across these, so the matrix also smoke-tests the derivation logic and
# the typedef-array static asserts that gate it.
#
# Backs up _opt/ssfec_opt.h and _opt/ssfrsa_opt.h on entry and restores via
# trap so an interrupted run does not leave the working tree dirty.
#
# Usage:  ./tools/config-matrix/run.sh
#         ./tools/config-matrix/run.sh -k    # keep going past a failure
#
# Exit:   0 if every config passes; 1 otherwise.

set -u

script_dir=$(cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(cd -- "$script_dir/../.." && pwd)
cd "$repo_root"

ec_opt=_opt/ssfec_opt.h
rsa_opt=_opt/ssfrsa_opt.h
ec_backup=$(mktemp -t ssfec_opt.XXXXXX)
rsa_backup=$(mktemp -t ssfrsa_opt.XXXXXX)
cp "$ec_opt" "$ec_backup"
cp "$rsa_opt" "$rsa_backup"

restore() {
    cp "$ec_backup" "$ec_opt"
    cp "$rsa_backup" "$rsa_opt"
    rm -f "$ec_backup" "$rsa_backup"
}
trap restore EXIT INT TERM

keep_going=0
if [ "${1:-}" = "-k" ]; then
    keep_going=1
fi

# Locate MSBuild (Windows / VS 2026 install). Override via $MSBUILD if needed.
msbuild=${MSBUILD:-}
if [ -z "$msbuild" ]; then
    for guess in \
        "/c/Program Files/Microsoft Visual Studio/18/Community/MSBuild/Current/Bin/MSBuild.exe" \
        "/c/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/MSBuild.exe" \
        "/c/Program Files/Microsoft Visual Studio/2022/Professional/MSBuild/Current/Bin/MSBuild.exe"; do
        if [ -x "$guess" ]; then
            msbuild=$guess
            break
        fi
    done
fi
if [ -z "$msbuild" ] || [ ! -x "$msbuild" ]; then
    echo "ERROR: MSBuild.exe not found. Set \$MSBUILD or install Visual Studio." >&2
    exit 64
fi

# Output a complete _opt/ssfec_opt.h with the requested ENABLE_* values. The
# FIXED_BASE_* flags are deliberately not specified so the auto-derivation in
# the file (which defaults each FIXED_BASE_X to ENABLE_X) takes effect.
write_ec_opt() {
    p256=$1
    p384=$2
    cat > "$ec_opt" <<EOF
/* --------------------------------------------------------------------------------------------- */
/* Generated by tools/config-matrix/run.sh — DO NOT EDIT (restored on script exit).               */
/* --------------------------------------------------------------------------------------------- */
#ifndef SSF_EC_OPT_H_INCLUDE
#define SSF_EC_OPT_H_INCLUDE

#ifdef __cplusplus
extern "C" {
#endif

#define SSF_EC_CONFIG_ENABLE_P256            (${p256}u)
#define SSF_EC_CONFIG_ENABLE_P384            (${p384}u)

#ifndef SSF_EC_CONFIG_FIXED_BASE_P256
#define SSF_EC_CONFIG_FIXED_BASE_P256        SSF_EC_CONFIG_ENABLE_P256
#endif
#ifndef SSF_EC_CONFIG_FIXED_BASE_P384
#define SSF_EC_CONFIG_FIXED_BASE_P384        SSF_EC_CONFIG_ENABLE_P384
#endif

#ifndef SSF_EC_FIXED_BASE_COMB_H
#define SSF_EC_FIXED_BASE_COMB_H             (6u)
#endif

#if (SSF_EC_CONFIG_FIXED_BASE_P256 == 1) && (SSF_EC_CONFIG_ENABLE_P256 == 0)
#error SSF_EC_CONFIG_FIXED_BASE_P256 requires SSF_EC_CONFIG_ENABLE_P256 to be 1.
#endif
#if (SSF_EC_CONFIG_FIXED_BASE_P384 == 1) && (SSF_EC_CONFIG_ENABLE_P384 == 0)
#error SSF_EC_CONFIG_FIXED_BASE_P384 requires SSF_EC_CONFIG_ENABLE_P384 to be 1.
#endif

#ifdef __cplusplus
}
#endif
#endif /* SSF_EC_OPT_H_INCLUDE */
EOF
}

write_rsa_opt() {
    r2048=$1
    r3072=$2
    r4096=$3
    cat > "$rsa_opt" <<EOF
/* --------------------------------------------------------------------------------------------- */
/* Generated by tools/config-matrix/run.sh — DO NOT EDIT (restored on script exit).               */
/* --------------------------------------------------------------------------------------------- */
#ifndef SSF_RSA_OPT_H_INCLUDE
#define SSF_RSA_OPT_H_INCLUDE

#ifdef __cplusplus
extern "C" {
#endif

#define SSF_RSA_CONFIG_ENABLE_2048           (${r2048}u)
#define SSF_RSA_CONFIG_ENABLE_3072           (${r3072}u)
#define SSF_RSA_CONFIG_ENABLE_4096           (${r4096}u)

#define SSF_RSA_CONFIG_ENABLE_KEYGEN         (1u)
#define SSF_RSA_CONFIG_ENABLE_PKCS1_V15      (1u)
#define SSF_RSA_CONFIG_ENABLE_PSS            (1u)
#define SSF_RSA_CONFIG_MILLER_RABIN_ROUNDS   (5u)

#ifdef __cplusplus
}
#endif
#endif /* SSF_RSA_OPT_H_INCLUDE */
EOF
}

# Run one config: build, run, report.
# Args: <name> <p256> <p384> <r2048> <r3072> <r4096>
results_file=$(mktemp -t ssf_matrix_results.XXXXXX)
overall=0
run_config() {
    name=$1
    p256=$2
    p384=$3
    r2048=$4
    r3072=$5
    r4096=$6

    printf "[%-32s] " "$name"
    write_ec_opt "$p256" "$p384"
    write_rsa_opt "$r2048" "$r3072" "$r4096"

    build_log=$(mktemp -t ssf_matrix_build.XXXXXX)
    "$msbuild" ssf.sln -nologo -m -v:minimal -p:Configuration=Debug -p:Platform=x64 \
        > "$build_log" 2>&1
    build_rc=$?
    if [ "$build_rc" -ne 0 ]; then
        printf "BUILD FAIL (rc=%s)\n" "$build_rc"
        echo "  build log: $build_log"
        echo "$name BUILD_FAIL" >> "$results_file"
        overall=1
        if [ "$keep_going" = "0" ]; then exit 1; fi
        return
    fi
    rm -f "$build_log"

    test_log=$(mktemp -t ssf_matrix_test.XXXXXX)
    x64/Debug/ssf.exe > "$test_log" 2>&1
    test_rc=$?
    passed=$(grep -cE "PASSED" "$test_log")
    failed=$(grep -cE "FAILED|Assert" "$test_log")
    if [ "$test_rc" -ne 0 ] || [ "$failed" -gt 0 ]; then
        printf "TEST FAIL (rc=%s, passed=%s, failed=%s)\n" "$test_rc" "$passed" "$failed"
        echo "  test log: $test_log"
        echo "$name TEST_FAIL passed=$passed failed=$failed" >> "$results_file"
        overall=1
        if [ "$keep_going" = "0" ]; then exit 1; fi
        return
    fi
    rm -f "$test_log"

    printf "OK (passed=%s)\n" "$passed"
    echo "$name OK passed=$passed" >> "$results_file"
}

echo "===== ssf config-matrix sweep ====="
echo "MSBuild: $msbuild"
echo

# name                          P256 P384 R2048 R3072 R4096
run_config "default-all-on"         1    1    1    1    1
run_config "pure-ECC-both"          1    1    0    0    0
run_config "pure-ECC-P256-only"     1    0    0    0    0
run_config "pure-ECC-P384-only"     0    1    0    0    0
run_config "RSA-2048+EC-both"       1    1    1    0    0
run_config "RSA-3072+EC-both"       1    1    0    1    0
run_config "RSA-4096+EC-both"       1    1    0    0    1
run_config "embedded-min(2048+P256)" 1    0    1    0    0

echo
echo "===== summary ====="
cat "$results_file"
rm -f "$results_file"

if [ "$overall" -eq 0 ]; then
    echo
    echo "ALL CONFIGURATIONS PASSED"
fi
exit "$overall"
