/* --------------------------------------------------------------------------------------------- */
/* Small System Framework                                                                        */
/*                                                                                               */
/* ssfec_p384_comb_table_h4.h                                                                  */
/* Precomputed Lim-Lee comb table for fixed-base P384 scalar multiplication.                  */
/*                                                                                               */
/* Layout: 16 entries x 2 coordinates (X, Y) x 12 limbs (32-bit, little-endian limb order).  */
/* h = 4 strips, d = 96 bits per strip. Entries are in AFFINE form (Z = 1 implicit).                */
/* Entry 0 is a sentinel; the comb runtime restores r from a saved copy when mask==0.            */
/*                                                                                               */
/* table[mask] = sum_{j: bit j of mask is set} G_j  where G_j = [2^(j*96)] G  for j in 0..3.    */
/*                                                                                               */
/* Auto-generated by tools/gen_comb.py -- do not edit by hand.                                    */
/*                                                                                               */
/* BSD-3-Clause License                                                                          */
/* Copyright 2026 Supurloop Software LLC                                                         */
/* --------------------------------------------------------------------------------------------- */
#ifndef SSF_EC_P384_COMB_TABLE_H4_INCLUDE
#define SSF_EC_P384_COMB_TABLE_H4_INCLUDE

static const SSFBNLimb_t _ssfECP384CombStorage[16][2][12] = {
    /* table[ 0] = O (identity sentinel; runtime restores r when mask==0) */
    {
        { 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u },
        { 0x00000001u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u },
    },
    /* table[ 1] = G_0 (affine) */
    {
        { 0x72760AB7u, 0x3A545E38u, 0xBF55296Cu, 0x5502F25Du, 0x82542A38u, 0x59F741E0u, 0x8BA79B98u, 0x6E1D3B62u, 0xF320AD74u, 0x8EB1C71Eu, 0xBE8B0537u, 0xAA87CA22u },
        { 0x90EA0E5Fu, 0x7A431D7Cu, 0x1D7E819Du, 0x0A60B1CEu, 0xB5F0B8C0u, 0xE9DA3113u, 0x289A147Cu, 0xF8F41DBDu, 0x9292DC29u, 0x5D9E98BFu, 0x96262C6Fu, 0x3617DE4Au },
    },
    /* table[ 2] = G_1 (affine) */
    {
        { 0xD8EE21C9u, 0x39C1B328u, 0x558717DBu, 0x2C3E0C91u, 0x3F8686A9u, 0x4B58808Bu, 0x18141B1Au, 0x43603909u, 0x37CA7ABCu, 0xD6E98B0Du, 0x060CBD1Bu, 0xF532389Au },
        { 0x23D86ECDu, 0x7A7E1839u, 0x085A4E9Au, 0x31EA31B1u, 0xBE643603u, 0xBC40CE5Au, 0xA2124163u, 0xBD22CFB2u, 0xDE3A82BAu, 0x6F04CAA2u, 0xC3B38E69u, 0xB9D2852Cu },
    },
    /* table[ 3] = G_0 + G_1 (affine) */
    {
        { 0xEB09A0E5u, 0x264E5246u, 0x32CDF03Cu, 0xF8F4BE11u, 0x5FAEFA4Fu, 0xDA9D5483u, 0x17A31B22u, 0xBBBC4FD0u, 0x86F06145u, 0xC3DECD0Cu, 0x0A5F2CABu, 0x528EF167u },
        { 0xC14F0DD6u, 0x8A1E9858u, 0x09CB7524u, 0x550538A8u, 0xC87FED22u, 0xBD60CAB4u, 0x631D058Du, 0xF8B76FDDu, 0x1A1DCF14u, 0x5803EAA1u, 0x7BCCF56Cu, 0x7B9B1FBEu },
    },
    /* table[ 4] = G_2 (affine) */
    {
        { 0xAA03BD53u, 0xA628B09Au, 0xA4F52D78u, 0xBA065458u, 0x4D10DDEAu, 0xDB298789u, 0x8A3E297Du, 0xB42A31AFu, 0x06421279u, 0x40F7F9E7u, 0x800119C4u, 0xC19E0B4Cu },
        { 0xE6C88C41u, 0x822D0FC5u, 0xE639D858u, 0xAF68AA6Du, 0x35F6EBF2u, 0xC1C7CAD1u, 0xE3567AF9u, 0x577A30EAu, 0x1F5B77F6u, 0xE5A0191Du, 0x0356B301u, 0x16F3FDBFu },
    },
    /* table[ 5] = G_0 + G_2 (affine) */
    {
        { 0xAA133909u, 0x30991560u, 0xC6CB0017u, 0x9097DBB1u, 0xB860FAE6u, 0xD37DE424u, 0x70B375DDu, 0x9BB183B2u, 0xCD6CE3A3u, 0x567A6233u, 0x0FDC3088u, 0xAAB8BB9Fu },
        { 0x600AD5A6u, 0x16C5B981u, 0xD62FAA44u, 0xEBDF73F2u, 0xC9747BF3u, 0x6D955BB3u, 0x15EB04ACu, 0xF6005FC8u, 0x282050B5u, 0xF0AF01D1u, 0x314F6D28u, 0x48942F81u },
    },
    /* table[ 6] = G_1 + G_2 (affine) */
    {
        { 0x7716605Eu, 0x20221121u, 0x9EF281C8u, 0x2347D2C8u, 0x567D6342u, 0x54BA4599u, 0x77C0F03Fu, 0xCE0FBA30u, 0xCB367444u, 0x7022F802u, 0xA9A6A052u, 0x7334A936u },
        { 0xD658A01Au, 0xB5461F68u, 0xC2BD0EFAu, 0x0A64D519u, 0x697A9280u, 0x9E2EEE8Fu, 0x7D0E017Au, 0x8E5D9B89u, 0x7CBD4CCDu, 0x1F7C5C36u, 0xF632C926u, 0x7FFCEFF7u },
    },
    /* table[ 7] = G_0 + G_1 + G_2 (affine) */
    {
        { 0x0E758344u, 0x300AE2E6u, 0x371A2CA5u, 0x451C707Au, 0x5052DD32u, 0x25651D10u, 0x4862B954u, 0xBF88DE7Fu, 0x0381EF13u, 0xFAFCE26Eu, 0x960E090Eu, 0xDC916C17u },
        { 0x026B0889u, 0xED17CC44u, 0x9B42441Bu, 0x95C01FF1u, 0xCC160697u, 0x40896478u, 0x0BA04A35u, 0x52D154B8u, 0x701C2952u, 0xB3D92EA4u, 0xD69ECA0Au, 0x266E8A40u },
    },
    /* table[ 8] = G_3 (affine) */
    {
        { 0x4905CA71u, 0xE4BFC2C0u, 0xD156F761u, 0xF33A450Au, 0xD08848C2u, 0x3D8B29DBu, 0xA2309686u, 0x097DA395u, 0x5F4972D7u, 0x21190503u, 0x17CBAA12u, 0xB2D10558u },
        { 0x753EE324u, 0xDDCEBB55u, 0x6924666Fu, 0xE87AB07Cu, 0x4ECF1A68u, 0x9B475D74u, 0x2E6236C0u, 0xF82BE8F5u, 0x3CFD056Bu, 0x237C0DBAu, 0xC3C6CBD2u, 0x354CD872u },
    },
    /* table[ 9] = G_0 + G_3 (affine) */
    {
        { 0x708D4CEEu, 0x8D104D24u, 0x819CF043u, 0x197D6958u, 0xF0712210u, 0x47FC87FAu, 0x5C201558u, 0x103DF785u, 0x611EF638u, 0x30B0A9E8u, 0xFDFEBFECu, 0x00B19AC8u },
        { 0xD201E03Eu, 0xD40E8D6Fu, 0x2228FF5Fu, 0xBB7C969Cu, 0x636164C5u, 0x68810282u, 0xE754220Du, 0xCDBB3CD2u, 0xE9F6EDC4u, 0x1418FE25u, 0x9EE36031u, 0xA72F9105u },
    },
    /* table[10] = G_1 + G_3 (affine) */
    {
        { 0xB769737Au, 0x64D2C273u, 0x97D53FFDu, 0x2CC02451u, 0xE86C46BDu, 0xC3B6AC4Bu, 0x685E926Du, 0x17E9411Fu, 0x75203A36u, 0x136DF36Bu, 0x8BF0B27Eu, 0x3F9561E0u },
        { 0x27E990A7u, 0xDD6FF8D5u, 0xF9867A60u, 0xC34BE586u, 0x8554E014u, 0xEA088747u, 0x6F52E4CBu, 0xCFCED664u, 0x412AB641u, 0x4B1A5A20u, 0x39629587u, 0x0B06F006u },
    },
    /* table[11] = G_0 + G_1 + G_3 (affine) */
    {
        { 0x85651F82u, 0x044C0DD2u, 0x785D3EF7u, 0x325C51E7u, 0x88E95532u, 0xB83A1861u, 0x522C2931u, 0x539F94ADu, 0x8980F137u, 0x15274E5Bu, 0xDF0F66D7u, 0x9FD7B010u },
        { 0x4064E4C0u, 0xE4A7B94Au, 0x25D7D211u, 0xD44EBA45u, 0xBE8A04E3u, 0x0A806B54u, 0x149033DEu, 0x929226BDu, 0xC9739246u, 0x795F6FA3u, 0xB9260225u, 0x321AA9A3u },
    },
    /* table[12] = G_2 + G_3 (affine) */
    {
        { 0x8B707B8Eu, 0x49BCC2F5u, 0x1D928983u, 0x2901B519u, 0x7D49C780u, 0x2E4C2956u, 0x4C6A9964u, 0xEBD1CFF8u, 0x16EE3E13u, 0x2CAEBBD3u, 0xA87A68F7u, 0x36A543EEu },
        { 0xB569946Du, 0x75B41C29u, 0x3EF2267Eu, 0x1510E7D4u, 0xD4B3394Du, 0x91235072u, 0x8FBD85D1u, 0x58EAFF04u, 0x78A67847u, 0xD349AB03u, 0xA50EE41Cu, 0xF277BACDu },
    },
    /* table[13] = G_0 + G_2 + G_3 (affine) */
    {
        { 0x5F863BBDu, 0x10B05658u, 0xB483283Du, 0xE92CDC5Au, 0xDC7C421Du, 0xEBB31209u, 0x6D01A5A8u, 0x3AFCBD79u, 0xA08B6A51u, 0xE2B067CAu, 0xE8CB7AEBu, 0x026E0DC2u },
        { 0x02DDE18Au, 0xD8C35029u, 0xD8C6CF36u, 0x64C15FACu, 0x10781E45u, 0x17EA2701u, 0x1F3443D8u, 0xD68D1FFCu, 0x8C7461A5u, 0x4BE25637u, 0xD8EF24E1u, 0xAE8866BAu },
    },
    /* table[14] = G_1 + G_2 + G_3 (affine) */
    {
        { 0xD265A91Cu, 0xAC3A78D0u, 0x6C8F83D3u, 0x1A29F8EFu, 0x8FD8D817u, 0xEF98FDDEu, 0xC42BF748u, 0xDF459EA1u, 0x81A73DC7u, 0x14DAFC39u, 0xC52AFA2Du, 0xB03DFA54u },
        { 0x6C0D2CE7u, 0xCC406F6Eu, 0x41FD72CAu, 0xCD120B2Bu, 0x78F602DDu, 0xEF5D9006u, 0x8ACCF229u, 0xF5F8A2D1u, 0xCE6D908Au, 0xAAFD1FCFu, 0x0E6D85F2u, 0x2CE2885Au },
    },
    /* table[15] = G_0 + G_1 + G_2 + G_3 (affine) */
    {
        { 0xC62666DEu, 0x89109A0Eu, 0x7FFCD01Eu, 0xC8C12E75u, 0xC48B5AB0u, 0xA8206169u, 0xF983AC6Cu, 0x4BC2FDCFu, 0x55977D23u, 0x59CFCA71u, 0x5766C96Au, 0x1264CB33u },
        { 0x2E014B4Bu, 0x6B691381u, 0xE4483EC5u, 0x31D28707u, 0xFFB19758u, 0xCBF7190Cu, 0x65A5F248u, 0xB66717A0u, 0xC53B4F69u, 0xD94AD8FAu, 0xA1A1A376u, 0x119EBEEEu },
    },
};

#endif /* SSF_EC_P384_COMB_TABLE_H4_INCLUDE */
