/* --------------------------------------------------------------------------------------------- */
/* Small System Framework                                                                        */
/*                                                                                               */
/* ssfec_p256_comb_table_h5.h                                                                  */
/* Precomputed Lim-Lee comb table for fixed-base P256 scalar multiplication.                  */
/*                                                                                               */
/* Layout: 32 entries x 2 coordinates (X, Y) x 8 limbs (32-bit, little-endian limb order).   */
/* h = 5 strips, d = 52 bits per strip. Entries are in AFFINE form (Z = 1 implicit).                */
/* Entry 0 is a sentinel; the comb runtime restores r from a saved copy when mask==0.            */
/*                                                                                               */
/* table[mask] = sum_{j: bit j of mask is set} G_j  where G_j = [2^(j*52)] G  for j in 0..4.    */
/*                                                                                               */
/* Auto-generated by tools/gen_comb.py — do not edit by hand.                                     */
/*                                                                                               */
/* BSD-3-Clause License                                                                          */
/* Copyright 2026 Supurloop Software LLC                                                         */
/* --------------------------------------------------------------------------------------------- */
#ifndef SSF_EC_P256_COMB_TABLE_H5_INCLUDE
#define SSF_EC_P256_COMB_TABLE_H5_INCLUDE

static const SSFBNLimb_t _ssfECP256CombStorage[32][2][8] = {
    /* table[ 0] = O (identity sentinel; runtime restores r when mask==0) */
    {
        { 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u },
        { 0x00000001u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u },
    },
    /* table[ 1] = G_0 (affine) */
    {
        { 0xD898C296u, 0xF4A13945u, 0x2DEB33A0u, 0x77037D81u, 0x63A440F2u, 0xF8BCE6E5u, 0xE12C4247u, 0x6B17D1F2u },
        { 0x37BF51F5u, 0xCBB64068u, 0x6B315ECEu, 0x2BCE3357u, 0x7C0F9E16u, 0x8EE7EB4Au, 0xFE1A7F9Bu, 0x4FE342E2u },
    },
    /* table[ 2] = G_1 (affine) */
    {
        { 0x071E5C83u, 0xEEA6BC92u, 0x8542A0BEu, 0x8BD27F19u, 0x2A58E5B1u, 0x20A845B7u, 0x5026D73Fu, 0x54CCC941u },
        { 0x140916A1u, 0xCFD08EF7u, 0x5D8EE496u, 0x929E0BCCu, 0xDAD2BF22u, 0x3A8F8715u, 0xB4514532u, 0x1C433F45u },
    },
    /* table[ 3] = G_0 + G_1 (affine) */
    {
        { 0x04BAC870u, 0xF7D24BB7u, 0x3A23C6ABu, 0x593A09A0u, 0xF94C9D1Du, 0xDFCC2358u, 0x297BED02u, 0x3CFA0F87u },
        { 0x40F26940u, 0xCE98A30Bu, 0x0248A8AFu, 0x62121C0Du, 0x8309AF9Bu, 0xA758AA80u, 0x70BE12C6u, 0xE4E37694u },
    },
    /* table[ 4] = G_2 (affine) */
    {
        { 0x3ECCA7E0u, 0xC739A5EAu, 0x6743333Eu, 0xA7D2C98Fu, 0x224D9428u, 0x0FEF6335u, 0x5C792A0Cu, 0x7EF2EE3Cu },
        { 0x552AC094u, 0x302B22DDu, 0xDFBD3D20u, 0x81B21450u, 0xD5E609DBu, 0xA4F67F51u, 0x30ACC011u, 0xAFB68627u },
    },
    /* table[ 5] = G_0 + G_2 (affine) */
    {
        { 0x86EF7D7Du, 0xDD37E3FFu, 0x088B86DBu, 0xF6D77C27u, 0x254C5491u, 0x28FE9A4Fu, 0x6DF0FD5Eu, 0xD6690337u },
        { 0xADDAD596u, 0x9FF04992u, 0x9E4373F9u, 0xF3D1A7AFu, 0xDF074167u, 0xA13E9578u, 0xE6D13D22u, 0x20E2A53Cu },
    },
    /* table[ 6] = G_1 + G_2 (affine) */
    {
        { 0xB0879605u, 0xD7B86AEEu, 0xBE3C7265u, 0xA424EC2Du, 0x12F01E9Eu, 0x276203C2u, 0xB77E46E9u, 0xB666FAC5u },
        { 0x3BF0C52Du, 0xF431BB1Au, 0x726CD8B6u, 0xEF46A44Au, 0xEE3DE5A9u, 0xEB5ABC19u, 0x90246904u, 0x38AAA380u },
    },
    /* table[ 7] = G_0 + G_1 + G_2 (affine) */
    {
        { 0x525D6ABFu, 0xAEBFD735u, 0x96BEA25Au, 0xC302F8F4u, 0x544920A4u, 0xDB82B3EAu, 0x02EADB2Eu, 0x621C75D1u },
        { 0x9EF485F0u, 0x8939DC4Cu, 0x57C46D63u, 0x225D03D8u, 0x522D7F70u, 0x4FDAC96Fu, 0xB4FA649Du, 0xD7C4A4FEu },
    },
    /* table[ 8] = G_3 (affine) */
    {
        { 0x943E832Au, 0x9C762EF1u, 0x1786DF70u, 0x07E50AB0u, 0x2589F18Eu, 0x90F573A8u, 0xA7C2A51Au, 0x0D2BF28Bu },
        { 0x5B20D37Cu, 0x48263AF1u, 0x60551446u, 0x27EC9DB9u, 0x94B4E7EDu, 0x7087A10Au, 0x13BD00ACu, 0x0CAC3F43u },
    },
    /* table[ 9] = G_0 + G_3 (affine) */
    {
        { 0xC0B9372Au, 0x8BC659AAu, 0xEDD9583Fu, 0xF7659958u, 0x8C267D88u, 0x9F05F94Au, 0xC99A739Du, 0x00DC46E7u },
        { 0xDF55D0F2u, 0x4AF50A00u, 0x8156BF6Au, 0xB5EB202Du, 0x5228C111u, 0x40D1E3ABu, 0x45793424u, 0x0312A557u },
    },
    /* table[10] = G_1 + G_3 (affine) */
    {
        { 0x9E6486E0u, 0x9D90CDA8u, 0x1C7522C0u, 0xC8A820BDu, 0x08DCD7ABu, 0x867C5580u, 0x882A7892u, 0x3C510CE2u },
        { 0x646D54C6u, 0x0E283334u, 0xEDA4E046u, 0x33392776u, 0x5BA997B0u, 0xC3A7FC08u, 0x5ACF053Fu, 0xD35E620Fu },
    },
    /* table[11] = G_0 + G_1 + G_3 (affine) */
    {
        { 0x7EB8CFEEu, 0x8D9692F7u, 0x0D8C013Du, 0x05E3F223u, 0x84E32E59u, 0x76347A52u, 0x15B0A1E5u, 0x3C53E290u },
        { 0xFAE798D4u, 0x538B7DA5u, 0x00D23591u, 0x1B9F1BD1u, 0x9A08693Fu, 0x11A9F072u, 0x140EFEB3u, 0xD30E7CDAu },
    },
    /* table[12] = G_2 + G_3 (affine) */
    {
        { 0x4DD6C004u, 0x81DEC926u, 0xDAD210D5u, 0xBFED14FEu, 0xB96B9911u, 0x39F9FF69u, 0x29C2024Du, 0x02FD7B73u },
        { 0x715D29FCu, 0x50CFCEB8u, 0x0C236311u, 0xB682B999u, 0xC7797831u, 0x00F34ADDu, 0x59927DF3u, 0x42EBD3CBu },
    },
    /* table[13] = G_0 + G_2 + G_3 (affine) */
    {
        { 0xF8E8F683u, 0x6DFCF787u, 0x3F7FBE90u, 0x13D72B7Au, 0x2DF232CFu, 0xFD426D94u, 0x5FE39AADu, 0xED84BB42u },
        { 0x732995FCu, 0x023E67A1u, 0x355430E3u, 0x67DD0A8Eu, 0x97A1D703u, 0x0CF83B61u, 0x583C33F2u, 0xA3233455u },
    },
    /* table[14] = G_1 + G_2 + G_3 (affine) */
    {
        { 0x68142904u, 0x27014AB4u, 0x00CFA617u, 0xFB500882u, 0x7009B958u, 0x6745FF87u, 0xD449242Du, 0x9E9889BCu },
        { 0x575616C8u, 0x035B613Bu, 0x138E99E2u, 0x00855156u, 0x292E6AA0u, 0x94C0D24Bu, 0x7E79B3A2u, 0xD9BA5B68u },
    },
    /* table[15] = G_0 + G_1 + G_2 + G_3 (affine) */
    {
        { 0x5F165D99u, 0xCEBBBC7Bu, 0x8A4EEE61u, 0x50CC51C1u, 0x1B4D0D1Fu, 0xB31D2353u, 0x66382ADAu, 0x95E18452u },
        { 0x0A839B5Bu, 0xACAD4F81u, 0x4142FF0Fu, 0xA0A2A96Eu, 0x1F4FA12Fu, 0x3EAA8289u, 0x6B0FB8F3u, 0x68D68C8Fu },
    },
    /* table[16] = G_4 (affine) */
    {
        { 0x839BB85Fu, 0x320F09C3u, 0xA050E62Cu, 0x0101FB06u, 0x9AD53458u, 0x557582C9u, 0x1666432Bu, 0x55D5398Du },
        { 0x4FED936Fu, 0xF7F63118u, 0x1833D9E1u, 0xD90D6A7Fu, 0x8EBAA72Au, 0x059C6A9Eu, 0x49FF8E2Du, 0x576E2290u },
    },
    /* table[17] = G_0 + G_4 (affine) */
    {
        { 0x51BBB3F1u, 0x9311A269u, 0x8D0F4F65u, 0xE80F26BDu, 0x6BECCBB9u, 0x9D3DC334u, 0x101E5DE4u, 0x54E244D5u },
        { 0xF1B19E28u, 0xB3AD4C6Eu, 0x58C2E3B7u, 0x4334FBC0u, 0x35DF9C25u, 0x19BD4107u, 0xEC106EB6u, 0xD6BBEC0Eu },
    },
    /* table[18] = G_1 + G_4 (affine) */
    {
        { 0xE5046DC5u, 0x788251C7u, 0xF179327Bu, 0x12839B95u, 0x4A8CB46Eu, 0xF1C05D98u, 0x3C00736Bu, 0x443737CDu },
        { 0x12CD8FE5u, 0xA760A456u, 0x0817BDD9u, 0x797489DEu, 0xF42C23E8u, 0xC56EB80Au, 0xE6FE7AF5u, 0x83719DD7u },
    },
    /* table[19] = G_0 + G_1 + G_4 (affine) */
    {
        { 0x3FEFCFC8u, 0xE8881A83u, 0xB9B5290Bu, 0xAEA3C9E0u, 0x771E4688u, 0x10B37ECDu, 0xD4D021B6u, 0xEE0816A3u },
        { 0xB3A8CAA1u, 0x8E9929BFu, 0xC105F2D1u, 0x48915DCFu, 0xDB49019Fu, 0x3A5FDF82u, 0xAD9006E1u, 0xC4A438E3u },
    },
    /* table[20] = G_2 + G_4 (affine) */
    {
        { 0x87DE4B29u, 0x5DB9620Fu, 0xD91ECB2Eu, 0xD7420C18u, 0x32ACF105u, 0x301BA1B2u, 0x7853A937u, 0xDB96BB0Cu },
        { 0xC359AC34u, 0xD84BFEF6u, 0x64852A1Du, 0xAB80CEF0u, 0xB9DA1717u, 0x3FBEE4D3u, 0x7A13222Cu, 0xB325074Eu },
    },
    /* table[21] = G_0 + G_2 + G_4 (affine) */
    {
        { 0xE83AD2C9u, 0x5D6DC503u, 0xAED035BEu, 0xCA9F7A1Du, 0xCBD21E33u, 0x552788ACu, 0xE09CB9F0u, 0x8699DD31u },
        { 0x329BF961u, 0x38584196u, 0xB82A5AF9u, 0x4CB20E96u, 0xC72C78C1u, 0x24199908u, 0xE92859B7u, 0x16E65484u },
    },
    /* table[22] = G_1 + G_2 + G_4 (affine) */
    {
        { 0x052FDE29u, 0x6A201C4Bu, 0x0031DBB4u, 0x6C897123u, 0x16C1DA96u, 0x4A759982u, 0x2CC67214u, 0xEEC0B975u },
        { 0x812C864Eu, 0xB908B9F1u, 0x8439F6BAu, 0x367FB66Au, 0xF966F329u, 0x789D664Bu, 0xF7F1D283u, 0xE02AF770u },
    },
    /* table[23] = G_0 + G_1 + G_2 + G_4 (affine) */
    {
        { 0xDB3038DDu, 0xA20A2C70u, 0xE99D5C7Cu, 0x5F0B46D5u, 0x4B600B83u, 0xC9B97D37u, 0x3DF3245Eu, 0x186C7F79u },
        { 0x4F1CE57Fu, 0x2AF72460u, 0x91E2D8EDu, 0x9249897Fu, 0x8D2EA797u, 0x8139B36Au, 0x9AB58913u, 0x9C428DB8u },
    },
    /* table[24] = G_3 + G_4 (affine) */
    {
        { 0x6471AAA0u, 0xB4A196FBu, 0x1B6B9730u, 0xDCBAB650u, 0x295B57D2u, 0x7AFCCC8Au, 0x4E33A65Du, 0xEE2280F4u },
        { 0x890FCD12u, 0xC47A0803u, 0x82604F6Bu, 0x4E98A98Du, 0xED5FBBD2u, 0x0D598F06u, 0xA6A1EB84u, 0xCE46EC91u },
    },
    /* table[25] = G_0 + G_3 + G_4 (affine) */
    {
        { 0x4BE6458Du, 0x1F1E4F3Fu, 0x595E6547u, 0x5F72CC22u, 0x271A93F1u, 0x5BC5341Eu, 0x58A5F263u, 0xC62E155Cu },
        { 0x58BA7FF4u, 0x5F6F845Au, 0x7E36A6ADu, 0x67E1F7DCu, 0xEEAA4D04u, 0xD33A7657u, 0x18267E4Eu, 0xFF9F2322u },
    },
    /* table[26] = G_1 + G_3 + G_4 (affine) */
    {
        { 0x4A53789Fu, 0xD369F11Fu, 0x3696B437u, 0xC7876FB6u, 0x0BABA29Au, 0xA0E8F0A7u, 0x32F6E514u, 0xA0318A5Fu },
        { 0x11775A08u, 0x5C4A43D1u, 0x362EEBB1u, 0x418C507Cu, 0x09A325AAu, 0xFD08903Fu, 0xF0EEBB3Au, 0xF320B8FCu },
    },
    /* table[27] = G_0 + G_1 + G_3 + G_4 (affine) */
    {
        { 0xC7644C1Du, 0xE33F0255u, 0xBB9002D8u, 0x4030ECC3u, 0xF4646F9Fu, 0xA4486916u, 0x959C44FAu, 0x5E677D0Cu },
        { 0xD88B9144u, 0xE2E7D7D0u, 0x6248F91Fu, 0x5D93A86Fu, 0x02993AEAu, 0xE33D0BD5u, 0x3100D31Eu, 0x449F0CE6u },
    },
    /* table[28] = G_2 + G_3 + G_4 (affine) */
    {
        { 0x73CF2678u, 0x3FCD925Au, 0xA6D0AFC7u, 0x34CA923Bu, 0x3067791Fu, 0x9011091Du, 0x5A7941E4u, 0x8C568874u },
        { 0xFC339800u, 0x34D37180u, 0x595C51F4u, 0x7744316Bu, 0xE88C6420u, 0xF2DDB693u, 0x5BAD14D2u, 0xFB3A48B1u },
    },
    /* table[29] = G_0 + G_2 + G_3 + G_4 (affine) */
    {
        { 0xFDAAB256u, 0x52DF1588u, 0x3127354Cu, 0x68C0CD44u, 0xA591F853u, 0x2A849471u, 0x93D0CB92u, 0xE4DA88E9u },
        { 0x1639C624u, 0x6D1EA35Du, 0x263707BAu, 0x60FE2A36u, 0xD0F3BC51u, 0x97FC50DEu, 0x10062E80u, 0xF7FA4D15u },
    },
    /* table[30] = G_1 + G_2 + G_3 + G_4 (affine) */
    {
        { 0x024C168Du, 0xC429A113u, 0x3FEAA272u, 0xB6C935FBu, 0xE639EC09u, 0xB58A6071u, 0xF9C13DE7u, 0x4B59253Au },
        { 0xFBFB8955u, 0x6D2D68F2u, 0x50723FE2u, 0xF0064C12u, 0x01F185F5u, 0xE85D7820u, 0x7FA79C93u, 0xAA0307BFu },
    },
    /* table[31] = G_0 + G_1 + G_2 + G_3 + G_4 (affine) */
    {
        { 0x5B696527u, 0x2E75A266u, 0x5A00169Cu, 0x1A2530B0u, 0x4286FB42u, 0x76C4C180u, 0x8E831D5Bu, 0x825F0194u },
        { 0xEF703739u, 0xDBF0A11Fu, 0xCE5B106Au, 0x106F9BC4u, 0x24111150u, 0x61794C4Fu, 0xBC723A17u, 0x435872FEu },
    },
};

#endif /* SSF_EC_P256_COMB_TABLE_H5_INCLUDE */
