/* --------------------------------------------------------------------------------------------- */
/* Small System Framework                                                                        */
/*                                                                                               */
/* ssfec_p256_comb_table_h6.h                                                                  */
/* Precomputed Lim-Lee comb table for fixed-base P256 scalar multiplication.                  */
/*                                                                                               */
/* Layout: 64 entries x 2 coordinates (X, Y) x 8 limbs (32-bit, little-endian limb order).   */
/* h = 6 strips, d = 43 bits per strip. Entries are in AFFINE form (Z = 1 implicit).                */
/* Entry 0 is a sentinel; the comb runtime restores r from a saved copy when mask==0.            */
/*                                                                                               */
/* table[mask] = sum_{j: bit j of mask is set} G_j  where G_j = [2^(j*43)] G  for j in 0..5.    */
/*                                                                                               */
/* Auto-generated by tools/gen_comb.py -- do not edit by hand.                                    */
/*                                                                                               */
/* BSD-3-Clause License                                                                          */
/* Copyright 2026 Supurloop Software LLC                                                         */
/* --------------------------------------------------------------------------------------------- */
#ifndef SSF_EC_P256_COMB_TABLE_H6_INCLUDE
#define SSF_EC_P256_COMB_TABLE_H6_INCLUDE

static const SSFBNLimb_t _ssfECP256CombStorage[64][2][8] = {
    /* table[ 0] = O (identity sentinel; runtime restores r when mask==0) */
    {
        { 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u },
        { 0x00000001u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u },
    },
    /* table[ 1] = G_0 (affine) */
    {
        { 0xD898C296u, 0xF4A13945u, 0x2DEB33A0u, 0x77037D81u, 0x63A440F2u, 0xF8BCE6E5u, 0xE12C4247u, 0x6B17D1F2u },
        { 0x37BF51F5u, 0xCBB64068u, 0x6B315ECEu, 0x2BCE3357u, 0x7C0F9E16u, 0x8EE7EB4Au, 0xFE1A7F9Bu, 0x4FE342E2u },
    },
    /* table[ 2] = G_1 (affine) */
    {
        { 0xB049E7CDu, 0xCD013F88u, 0xE57FDC00u, 0xE8F9257Au, 0xFC3A9301u, 0x3BE71969u, 0x58CFF937u, 0x987F256Du },
        { 0x6EFA35D6u, 0xB7254BBCu, 0x07AAFFDBu, 0x47B46052u, 0x0007E39Eu, 0xE860EBD6u, 0x94EC505Cu, 0x8E926956u },
    },
    /* table[ 3] = G_0 + G_1 (affine) */
    {
        { 0x5A1C3FB1u, 0x59DB167Cu, 0xBF318EB2u, 0x98B3CE2Au, 0xD2BC2FA6u, 0x2DF1C41Eu, 0x6ED1B2AFu, 0xEFCC2C43u },
        { 0x97B25513u, 0x17FE07F1u, 0x3734A589u, 0x46824533u, 0xED34F543u, 0xA5384A77u, 0x8D9F3863u, 0xF3684F9Cu },
    },
    /* table[ 4] = G_2 (affine) */
    {
        { 0xBF780C2Cu, 0xFDC73E83u, 0x2D666817u, 0xFFDC6794u, 0x02436893u, 0xC14B66DDu, 0x0D54650Cu, 0x6EEC9567u },
        { 0xEDBFCD32u, 0x089EC1A1u, 0x3A07FF89u, 0x79AB6615u, 0x65EA0105u, 0xFC281DE0u, 0x997732C2u, 0x14BB5350u },
    },
    /* table[ 5] = G_0 + G_2 (affine) */
    {
        { 0x7318188Eu, 0xAEC90264u, 0xCA167099u, 0x410BEC28u, 0x099C202Bu, 0xBF664D2Fu, 0x55FA625Cu, 0x13CCCA34u },
        { 0x05421C0Cu, 0xAA84C231u, 0x6CDB0D71u, 0x6B647521u, 0xFB216A5Eu, 0xE90446B1u, 0xAF46893Du, 0x4B5BA5A5u },
    },
    /* table[ 6] = G_1 + G_2 (affine) */
    {
        { 0x4862C5DBu, 0xACA2FA08u, 0xA1717F8Au, 0xDDFFC222u, 0xE4E09FD2u, 0xAB839A14u, 0x980330F5u, 0xF86A9078u },
        { 0xC1DD7DCCu, 0x6890F24Cu, 0xEA6EFD98u, 0xF75DCCFAu, 0xFF9A093Bu, 0xBA2612B8u, 0x2568653Cu, 0x20347D0Cu },
    },
    /* table[ 7] = G_0 + G_1 + G_2 (affine) */
    {
        { 0xCBDB1C78u, 0xD3B22809u, 0x30F6CDA4u, 0x5591C8EBu, 0xBFE80F8Bu, 0xB6E28740u, 0x40E7E7E7u, 0x0F74342Au },
        { 0x351C51F2u, 0xD2968E87u, 0xF5E17B5Eu, 0x65C5C581u, 0x9D994E2Eu, 0x6F58F02Au, 0xF5C1EC07u, 0x531C0B00u },
    },
    /* table[ 8] = G_3 (affine) */
    {
        { 0x1A6B665Eu, 0xEB042121u, 0xA7F6803Au, 0x802F779Eu, 0x3C0804C3u, 0x47501F2Au, 0x4945A1D4u, 0xA263919Bu },
        { 0x30BCDCFBu, 0x9EE40400u, 0x4C00EFE2u, 0xAC3F83DFu, 0xE60D60C5u, 0x2E9D3C9Du, 0x2AED20FCu, 0x873200BDu },
    },
    /* table[ 9] = G_0 + G_3 (affine) */
    {
        { 0x8B21AA51u, 0x2B52C47Du, 0x5A7E870Du, 0x0F503629u, 0x88B45127u, 0xBAA92814u, 0xC402E050u, 0x27D6451Eu },
        { 0x5567432Du, 0x5C96EC14u, 0x0F4150C7u, 0xCDEB9829u, 0xCDEEF566u, 0x5D91740Cu, 0x1BE9E583u, 0x2A58FA5Eu },
    },
    /* table[10] = G_1 + G_3 (affine) */
    {
        { 0x5788C0F6u, 0xD8142DFFu, 0x247FDE25u, 0x89BF5229u, 0x14E2280Fu, 0x5C971DDBu, 0x09904E3Fu, 0x785B7E91u },
        { 0x2E7E6F0Bu, 0x445E4519u, 0x4CE293DDu, 0x8789440Eu, 0xC797BE30u, 0x96B84F57u, 0xFA3EA32Du, 0x6B44059Du },
    },
    /* table[11] = G_0 + G_1 + G_3 (affine) */
    {
        { 0x2195A979u, 0x73B7C550u, 0xB8DD5813u, 0x2D7ED474u, 0xE104E9ACu, 0xC0B9ECD2u, 0xA2BD0ED8u, 0xDC90D975u },
        { 0x4DD6EB2Eu, 0x9FB55203u, 0xC01DFDE8u, 0x50D554BBu, 0xF0977A30u, 0x4CFD3277u, 0x815374C4u, 0xC87CE232u },
    },
    /* table[12] = G_2 + G_3 (affine) */
    {
        { 0xCF9A3CA9u, 0xE4B541B6u, 0x08B49B2Fu, 0x1C650587u, 0xF552641Eu, 0xB95F91B3u, 0x5C301277u, 0xBDDC23ACu },
        { 0x04DABA43u, 0x519D0700u, 0x8450CFA2u, 0xC003DCC3u, 0x4E48EFDEu, 0x73A1C8F5u, 0x5B04F761u, 0x7D0CA942u },
    },
    /* table[13] = G_0 + G_2 + G_3 (affine) */
    {
        { 0x1703406Du, 0xCB4DC35Bu, 0x75DAC54Cu, 0x4FD3AFC9u, 0x29F02878u, 0x112321EBu, 0xAD6B225Fu, 0xAFB18D2Fu },
        { 0xF1776A67u, 0xDDF58273u, 0xF6B96C2Fu, 0x96889755u, 0x22208FFBu, 0x31A8D663u, 0xFCCA4877u, 0x5ED81C10u },
    },
    /* table[14] = G_1 + G_2 + G_3 (affine) */
    {
        { 0xE834A3C4u, 0xFF0E1F34u, 0x1C4AB236u, 0x0D59B6AEu, 0x015A211Bu, 0x10EB194Au, 0x3892DDC5u, 0xED6E13E0u },
        { 0xFB3F678Du, 0xAC88DF04u, 0x544026A9u, 0x6F0FBF44u, 0x619CECBAu, 0xCDE8CD7Au, 0x80D9A8CCu, 0x02F322E5u },
    },
    /* table[15] = G_0 + G_1 + G_2 + G_3 (affine) */
    {
        { 0x336AAF40u, 0x2DC61E1Bu, 0x4251F5B7u, 0x897E87BDu, 0x6511B370u, 0x2FB32023u, 0x2341F499u, 0x460FA9CFu },
        { 0xCBAF01A7u, 0x03E63B79u, 0x44157434u, 0x937E123Fu, 0x809E4A1Au, 0x9D59226Eu, 0x41775E62u, 0x18D6F63Au },
    },
    /* table[16] = G_4 (affine) */
    {
        { 0xA9AA52DFu, 0x3CD5F4E4u, 0xB42A627Fu, 0x18C452B1u, 0xD991ECE6u, 0x6DBC4189u, 0x7F608BF7u, 0x45A511C9u },
        { 0x125EC16Cu, 0x7B52BD12u, 0xD22955CEu, 0x5A919B27u, 0xCB625AD2u, 0x3FE3337Fu, 0x73EA9B6Du, 0x73BE0EC7u },
    },
    /* table[17] = G_0 + G_4 (affine) */
    {
        { 0x016476EAu, 0xC6E4B6D0u, 0xD4EC2510u, 0x71B9A7E5u, 0xCBE490D2u, 0x1975B71Eu, 0xB52ACD25u, 0xDF6B472Fu },
        { 0x784055EBu, 0xF1738716u, 0xB87D399Eu, 0xCCC7B0B3u, 0x1BB51119u, 0x3C9A1337u, 0xA88FD593u, 0xB42639E1u },
    },
    /* table[18] = G_1 + G_4 (affine) */
    {
        { 0xC219C20Bu, 0x86A38D54u, 0xB50A4733u, 0xAFCDD2CAu, 0x72096638u, 0xF4CF8797u, 0x24CE0E94u, 0xD949CAA2u },
        { 0x96F9AE13u, 0x678664AEu, 0xC984DE46u, 0x00EF5BA9u, 0x8D549567u, 0x622ABC7Fu, 0x57DB924Du, 0x673ED500u },
    },
    /* table[19] = G_0 + G_1 + G_4 (affine) */
    {
        { 0x20B4D697u, 0x41E94206u, 0x29FA0DF9u, 0xA10FD0D9u, 0x76022C38u, 0xF11EB0A7u, 0xA5621C63u, 0xFFCB7DDCu },
        { 0x0927965Au, 0x24E37B1Bu, 0xBD2C199Eu, 0x8D9FC102u, 0x907F3F85u, 0x862DE75Eu, 0x5A9C778Eu, 0xD3985129u },
    },
    /* table[20] = G_2 + G_4 (affine) */
    {
        { 0xB56BC451u, 0x48D63748u, 0xA939440Au, 0x0544DE81u, 0x664EC19Cu, 0xDA24EB0Bu, 0x41F42BF6u, 0x4FB6E562u },
        { 0x66BB5D6Bu, 0x21B2C80Eu, 0xD25BD41Bu, 0xA4123924u, 0xBCE2D418u, 0x6F95F5F2u, 0x4D6D91D8u, 0xA9232776u },
    },
    /* table[21] = G_0 + G_2 + G_4 (affine) */
    {
        { 0xF119B8CCu, 0x546A08E7u, 0x8AFC696Au, 0x03B7D523u, 0x459F70B4u, 0x0A896132u, 0xA86A9116u, 0x57A46257u },
        { 0xBB314C65u, 0xFAA56FEFu, 0x74795C6Du, 0xF4E61F40u, 0x437850D6u, 0x1A3C5652u, 0x6621EC11u, 0x7C4B127Du },
    },
    /* table[22] = G_1 + G_2 + G_4 (affine) */
    {
        { 0xE83CFA35u, 0x6DD25E26u, 0x1FF3BDDCu, 0x61E44DA0u, 0x121733FAu, 0xB7B67B02u, 0xFCD798CAu, 0x7C48F60Du },
        { 0x090F5154u, 0x244D234Au, 0x8CAE33BBu, 0x93B7F2FBu, 0x426D1516u, 0x158BF2F6u, 0xA801E86Eu, 0xA8A947A8u },
    },
    /* table[23] = G_0 + G_1 + G_2 + G_4 (affine) */
    {
        { 0x56C8815Eu, 0xF41E0307u, 0x7D37A2F1u, 0xBAF647E3u, 0xFEFAFBF5u, 0x7791EB36u, 0x35B7F606u, 0x158262FBu },
        { 0x32DCE9E5u, 0xF6C32255u, 0x361B4780u, 0x6C7CD4CEu, 0x3F85288Fu, 0xE5BE5E70u, 0xC98E624Au, 0x4C281AA3u },
    },
    /* table[24] = G_3 + G_4 (affine) */
    {
        { 0x7FD58AE5u, 0x9D7F749Eu, 0x37EA57A2u, 0xC78BA263u, 0x4F5AB5B7u, 0xB5C05127u, 0x5F2D643Bu, 0x6FD3F54Du },
        { 0x2116B8CEu, 0x3428E311u, 0x71B28987u, 0xC52D1D24u, 0x8299421Fu, 0x87F70BE9u, 0x64F49798u, 0x0A5FD098u },
    },
    /* table[25] = G_0 + G_3 + G_4 (affine) */
    {
        { 0x4D6A3DEFu, 0x5B2911DDu, 0xB96008F1u, 0x4BEDD07Cu, 0xE36E7D64u, 0xEE748A6Fu, 0x4BBF5CF4u, 0xBFC49934u },
        { 0x8E74750Fu, 0x55C6F62Du, 0x48919902u, 0x22639F87u, 0x958A248Fu, 0xFA01AA94u, 0xED51AA40u, 0x2743AE8Au },
    },
    /* table[26] = G_1 + G_3 + G_4 (affine) */
    {
        { 0xE76CCBC0u, 0x75EA69CBu, 0xA762DEB7u, 0xC9736051u, 0xAF2BFF4Cu, 0xA720D4C6u, 0xBE6D6DBAu, 0x8E4C7B10u },
        { 0x2F128433u, 0xAF5C0EFEu, 0xA1FE85ECu, 0x834CBF1Fu, 0x2685F018u, 0xD321C5A6u, 0x717A5340u, 0xB5B09CF6u },
    },
    /* table[27] = G_0 + G_1 + G_3 + G_4 (affine) */
    {
        { 0x86EB7815u, 0x9CDDA821u, 0xCE413265u, 0x8C003612u, 0x91B577F5u, 0x8BCE1FABu, 0x488F730Cu, 0x0F3F29FFu },
        { 0xE6960D55u, 0xEBB08063u, 0xAECBF467u, 0x1A9699E2u, 0x4CE5761Bu, 0x6B1564A4u, 0x81382996u, 0x08F00EA5u },
    },
    /* table[28] = G_2 + G_3 + G_4 (affine) */
    {
        { 0x96BF8EA5u, 0x6C10CDD2u, 0xE8CD868Fu, 0xE28C488Au, 0x46442D00u, 0xBA9226C3u, 0xFA1F864Bu, 0x9125CAEDu },
        { 0x2E21B4AFu, 0xF33BD66Eu, 0x68DBE58Cu, 0x12DC5537u, 0xE5353044u, 0xD9B85123u, 0x07BC6B60u, 0xF4925BDEu },
    },
    /* table[29] = G_0 + G_2 + G_3 + G_4 (affine) */
    {
        { 0x70514A21u, 0x0D17FF39u, 0xDADD80EEu, 0xD2A7B5BAu, 0x8126C8C4u, 0x941E33C3u, 0x1D57C1DEu, 0xB9E156D0u },
        { 0xEA8105ADu, 0x220D500Du, 0x0202F3AEu, 0x6A2AA462u, 0x3DC96356u, 0x450056ABu, 0x452142C3u, 0x506AB6AAu },
    },
    /* table[30] = G_1 + G_2 + G_3 + G_4 (affine) */
    {
        { 0x1B20D599u, 0xE0CB1029u, 0x10A5FBA0u, 0x7B1ED83Du, 0x04007713u, 0x7D5FB32Bu, 0x79C82639u, 0x93BAB590u },
        { 0x49B97D9Du, 0x977FA5A6u, 0x3551254Au, 0xA3592333u, 0xA9F7A3EBu, 0x8F277388u, 0xE3026E2Cu, 0x36ABA935u },
    },
    /* table[31] = G_0 + G_1 + G_2 + G_3 + G_4 (affine) */
    {
        { 0xC05131CDu, 0xF197735Bu, 0x22BEB567u, 0x05650768u, 0xF7F55B1Fu, 0xDBF2B189u, 0x132C2614u, 0xAA144C82u },
        { 0xB3822251u, 0xF41CBE14u, 0xFFD0AFBEu, 0xB1CE72B2u, 0x844743FAu, 0x01A14D18u, 0x923739B8u, 0xC1D89FE3u },
    },
    /* table[32] = G_5 (affine) */
    {
        { 0x0B79847Du, 0xF0F679F1u, 0x6BB19BE6u, 0x3719A8B6u, 0xDC7F43D5u, 0x2DDB6C3Du, 0xDA0982E2u, 0x2800043Au },
        { 0x908D9EDAu, 0xFE5B0083u, 0xB8513AE9u, 0xA87058DBu, 0x84A4DC3Bu, 0xB6C07965u, 0x67E82909u, 0x0F991746u },
    },
    /* table[33] = G_0 + G_5 (affine) */
    {
        { 0x5F3F5B80u, 0x12416A5Cu, 0xDA522422u, 0x58E903DBu, 0x4291867Eu, 0x18CC80F1u, 0x7A152C2Bu, 0xB2035CF8u },
        { 0x95C80EDEu, 0x71125691u, 0xAF97C5B0u, 0xBFE02568u, 0x8A14E493u, 0x603E1DC5u, 0x749680DEu, 0xF12F359Cu },
    },
    /* table[34] = G_1 + G_5 (affine) */
    {
        { 0x6AA2B49Du, 0x1CAAB0BAu, 0x6F7FC502u, 0x6A75A768u, 0x57EA120Fu, 0x6A5EA5A8u, 0xDB6BDF96u, 0x998CD5F9u },
        { 0x467184A9u, 0xD2D7BA4Cu, 0x25C03723u, 0xBE178E54u, 0xBC389EF3u, 0x6BFC1707u, 0x7B7D9FB3u, 0x3256A8A0u },
    },
    /* table[35] = G_0 + G_1 + G_5 (affine) */
    {
        { 0xFEA77B0Cu, 0x40429D1Bu, 0x595E9A31u, 0x4651A4DCu, 0xE712693Au, 0x8900AAB1u, 0x84BF612Du, 0x90EA7767u },
        { 0x0D02F2B6u, 0xBDD10425u, 0xFB4D594Fu, 0xF5583BCCu, 0x5BA7B6A1u, 0x75754462u, 0x101E86F4u, 0xD1A321D3u },
    },
    /* table[36] = G_2 + G_5 (affine) */
    {
        { 0x5AC0B3DBu, 0x7A2F10B2u, 0xF0B98928u, 0xE6DEFFA0u, 0xE6B0B01Au, 0xB4B2939Bu, 0x0A3F2CA8u, 0xA03E1D52u },
        { 0x2CBEAD24u, 0xFC779531u, 0xD30FA3F9u, 0xE8362908u, 0xF23B00BBu, 0x6F29D6F4u, 0xEBB82E0Au, 0xEA1AD22Fu },
    },
    /* table[37] = G_0 + G_2 + G_5 (affine) */
    {
        { 0xE62DA069u, 0x6890B26Cu, 0x7C586265u, 0xA5702319u, 0x865672ABu, 0xE64E19BFu, 0xA07D9893u, 0xA66503F5u },
        { 0x21FE4743u, 0xE4DEB7C0u, 0x7D7100BEu, 0x3BAE847Du, 0xE17B1D29u, 0x1769FCA7u, 0x320AFC60u, 0xADBA60ECu },
    },
    /* table[38] = G_1 + G_2 + G_5 (affine) */
    {
        { 0x89806E19u, 0x74814E1Cu, 0xF9EC85DEu, 0x9135FC8Du, 0x09AFD25Bu, 0x0EE660A6u, 0x6740A284u, 0x943DE3B7u },
        { 0x622227D9u, 0xDBA0327Fu, 0xD4C486E8u, 0xA524C6D6u, 0x7134581Au, 0x217FB779u, 0xE4254A7Eu, 0xAFA3B65Fu },
    },
    /* table[39] = G_0 + G_1 + G_2 + G_5 (affine) */
    {
        { 0xC4E48158u, 0xA3C9D614u, 0xAE8FC508u, 0xB26B4A98u, 0x38B68E18u, 0x44EF8BE0u, 0xDB271FCDu, 0xBE9CF596u },
        { 0x8E6F95ADu, 0x737B653Eu, 0x9B9E4D0Au, 0x73DBE6FFu, 0xA4139F59u, 0x4B772A8Cu, 0x66C67E8Au, 0xA1F335E5u },
    },
    /* table[40] = G_3 + G_5 (affine) */
    {
        { 0x2D00715Bu, 0x0ABFA3EEu, 0xC8297B47u, 0xF3F65DC1u, 0x00669E85u, 0x4199B659u, 0x23C09567u, 0x7588DF7Fu },
        { 0x868D3227u, 0xABDF62FAu, 0x8099A8FCu, 0xA0844D34u, 0x3BABBC72u, 0x3361B9C0u, 0x6D5BF03Bu, 0xBB0357A4u },
    },
    /* table[41] = G_0 + G_3 + G_5 (affine) */
    {
        { 0xF77CF152u, 0xC0B161FBu, 0x8CE30043u, 0x243C4FEDu, 0x050E20DFu, 0xB1B4A2D0u, 0xC34999AEu, 0x5A61A286u },
        { 0x70214EB7u, 0x8C7BAF68u, 0xF2C261FEu, 0x975BCA7Du, 0x1ED91AE8u, 0x03C6DF31u, 0xA1380D38u, 0xE8CFAAADu },
    },
    /* table[42] = G_1 + G_3 + G_5 (affine) */
    {
        { 0x016F613Cu, 0xA6BCC84Du, 0xC2EC4E56u, 0xAE5CE038u, 0xF8BE76B4u, 0xAD80F035u, 0x84642DD4u, 0x00456C5Cu },
        { 0xDE3648C8u, 0x0EF7079Fu, 0x68D0A170u, 0x7BF0B3ABu, 0x56C684E3u, 0xA85C96B8u, 0x91D65C88u, 0xFD39B0F2u },
    },
    /* table[43] = G_0 + G_1 + G_3 + G_5 (affine) */
    {
        { 0x966D28DDu, 0xC79E3178u, 0x89F8A2C1u, 0x67BA8686u, 0x4ACF8D42u, 0xAF1F9C6Du, 0xE0847F7Du, 0x2D2B4273u },
        { 0x69130CECu, 0x1D9E1A90u, 0x9383E7B5u, 0x95CB10FDu, 0x44CC71AEu, 0x73438A26u, 0x1EE4EA49u, 0x37EAEB10u },
    },
    /* table[44] = G_2 + G_3 + G_5 (affine) */
    {
        { 0x620C767Bu, 0x2A675B54u, 0x5AE6598Eu, 0xF1235F08u, 0x48A35E9Bu, 0x3CF6A1CDu, 0xD8A1B5F8u, 0xF11A113Eu },
        { 0x1742A887u, 0xA401985Du, 0xB6A73D9Bu, 0x3F83BD07u, 0x82736067u, 0x3C7307A0u, 0x1F12FBB6u, 0x64A1A66Du },
    },
    /* table[45] = G_0 + G_2 + G_3 + G_5 (affine) */
    {
        { 0xD84A37DEu, 0x1C12B5CBu, 0xC7B1EA1Au, 0x56D66DB4u, 0x2CE31E9Au, 0x852BE420u, 0xE40FAF48u, 0x17BE9C2Du },
        { 0x38CC8797u, 0x735B3CCBu, 0x34B1093Eu, 0x1F8D9D80u, 0xE75B81C0u, 0xD8CC6E86u, 0x3FDBE697u, 0x6914BF94u },
    },
    /* table[46] = G_1 + G_2 + G_3 + G_5 (affine) */
    {
        { 0x0CCF3981u, 0x422618C9u, 0x8DAB3936u, 0x7F5F9610u, 0x8E0A6A28u, 0xCA4AB750u, 0xD5BAB133u, 0x8266E2FEu },
        { 0xAB5500F6u, 0xFAA7545Bu, 0x5D994D86u, 0xA91EDAEBu, 0x67FB462Du, 0x0A5B194Bu, 0x287178CEu, 0x089CFD68u },
    },
    /* table[47] = G_0 + G_1 + G_2 + G_3 + G_5 (affine) */
    {
        { 0x00B16F35u, 0x54B44D33u, 0x002D5707u, 0x59988EF3u, 0xD0494F94u, 0x256FE1EBu, 0x7F710DE4u, 0xAEF84169u },
        { 0x8BD49604u, 0xCA38FB1Fu, 0xBFA0B15Cu, 0xAEC9DAAEu, 0x642CF6DDu, 0x1551365Eu, 0x160E8FFFu, 0x75B8B0FAu },
    },
    /* table[48] = G_4 + G_5 (affine) */
    {
        { 0x01FEEA35u, 0xB2466027u, 0x317C61F1u, 0xEA17F580u, 0x786AACEBu, 0x8D71EABAu, 0x1CC47DABu, 0x7DE7454Au },
        { 0xFF1B1266u, 0x10B69D62u, 0xB9AB079Cu, 0xE22CC59Bu, 0x42B2D441u, 0x9A57E43Fu, 0xE8C85F85u, 0x22340FECu },
    },
    /* table[49] = G_0 + G_4 + G_5 (affine) */
    {
        { 0xEDAB9CB9u, 0x6033D113u, 0xE69D45EEu, 0x1DF87BA3u, 0xE4D65A03u, 0x93436236u, 0x3F98A508u, 0x5893F6F9u },
        { 0xAAD54FABu, 0xB3832E15u, 0x6BC7365Eu, 0x3277FF0Du, 0x200C4FB8u, 0xE8301118u, 0xD4E9384Du, 0x26E471BCu },
    },
    /* table[50] = G_1 + G_4 + G_5 (affine) */
    {
        { 0x68C28F39u, 0x1C1DD91Au, 0xF35669CAu, 0xFA494334u, 0x51ABB743u, 0x77B40ABDu, 0xE7873A25u, 0xEE7400BAu },
        { 0xED2309D9u, 0xF15D9BF5u, 0x3DA8785Au, 0x8A90D13Fu, 0x1BE8B67Du, 0x7E4FB96Cu, 0xCAE9ED81u, 0x196C1BA4u },
    },
    /* table[51] = G_0 + G_1 + G_4 + G_5 (affine) */
    {
        { 0xC52427D8u, 0x3276C5A4u, 0xF5A34B64u, 0x66958243u, 0xF36E0D92u, 0x04166798u, 0xC6E9E63Fu, 0x43E33927u },
        { 0xF0CA8D2Bu, 0x899AED76u, 0x0AF50DD8u, 0x43B89CDEu, 0x5951E13Bu, 0x805EA21Eu, 0x28413043u, 0xE210DAA4u },
    },
    /* table[52] = G_2 + G_4 + G_5 (affine) */
    {
        { 0x98A174FCu, 0xE17F627Bu, 0x4DFA285Eu, 0x5EBCE1FFu, 0x54C5F925u, 0xC95FE23Du, 0x3188BA78u, 0x5EA59A09u },
        { 0x2D2D8163u, 0x6615BB54u, 0x5DB03D95u, 0x37BE4A1Eu, 0x4FC47762u, 0xC51B5692u, 0xD142931Du, 0xB994CA42u },
    },
    /* table[53] = G_0 + G_2 + G_4 + G_5 (affine) */
    {
        { 0x0758035Bu, 0xCE46A165u, 0xE070A0C9u, 0xB33DF1ADu, 0x686934C9u, 0xBF01FB38u, 0xF0F16ED0u, 0x1CBA6257u },
        { 0xEE93409Cu, 0xE538A9B6u, 0x4A6B38DAu, 0xD82429A1u, 0xA5C215B1u, 0x1488770Du, 0x891D7658u, 0x4ADE1F8Eu },
    },
    /* table[54] = G_1 + G_2 + G_4 + G_5 (affine) */
    {
        { 0x51A03105u, 0xBF93CDA8u, 0x7BE433EDu, 0xB14F4A60u, 0xFA1C97A1u, 0x0AA4C4C3u, 0xBCED726Eu, 0xFE1A6375u },
        { 0x0409C304u, 0x4DB68287u, 0xEBF37AF4u, 0x08FB9622u, 0xF6ABDFF4u, 0x677003ECu, 0x3FB7CC37u, 0xE6B2E872u },
    },
    /* table[55] = G_0 + G_1 + G_2 + G_4 + G_5 (affine) */
    {
        { 0x27ADE63Fu, 0xFE702B4Bu, 0xA105673Au, 0x5DF11A33u, 0xA362B9CEu, 0x0D33CB80u, 0x855BB209u, 0xA7BB42F5u },
        { 0xC95FE575u, 0xFDCC6096u, 0x2351DEC6u, 0xFF0E08D7u, 0xBB6A5B28u, 0xA3323FF5u, 0x89F7A2ABu, 0x2CAA2DAEu },
    },
    /* table[56] = G_3 + G_4 + G_5 (affine) */
    {
        { 0x51FF89BBu, 0x252566B6u, 0xDB973DDCu, 0x453C333Eu, 0xD83F2CC2u, 0xFBCD5A09u, 0x3121DBD5u, 0x187818ECu },
        { 0x3B46B949u, 0xAEA1B45Fu, 0x55F753E0u, 0x42314623u, 0xB09991FAu, 0xD59AB00Bu, 0x0AE0C8D7u, 0xEE05650Du },
    },
    /* table[57] = G_0 + G_3 + G_4 + G_5 (affine) */
    {
        { 0x2DA7EB49u, 0x2096D676u, 0xFB775E41u, 0x6E04768Eu, 0xAF24F76Cu, 0xC3349C3Du, 0xDE0C90F6u, 0xE6DB6CCAu },
        { 0xA416FD87u, 0x98AA01F5u, 0x781EC427u, 0x84C3270Bu, 0x021034B2u, 0x37680F04u, 0x654BF735u, 0xEB90FE3Cu },
    },
    /* table[58] = G_1 + G_3 + G_4 + G_5 (affine) */
    {
        { 0xE4976DD8u, 0xEAF7623Cu, 0xE29BD0B4u, 0x92528B1Au, 0x645CEC2Au, 0x78158ECDu, 0xB11325E9u, 0x3265EAD8u },
        { 0xC04780B7u, 0x1CA27AF8u, 0x2465867Du, 0x14EF0845u, 0x2FEEFE38u, 0xB45C1887u, 0x5D8730E9u, 0x7C4D96BCu },
    },
    /* table[59] = G_0 + G_1 + G_3 + G_4 + G_5 (affine) */
    {
        { 0xB3571976u, 0x8E35BF16u, 0x346864E7u, 0xE2EB0C63u, 0x7E9B6C7Fu, 0x2B7B57E0u, 0x70B35A98u, 0x3157CF6Fu },
        { 0x5AC49EA5u, 0xFEC24C14u, 0x6B1A32AEu, 0xC20C5690u, 0x345FA335u, 0xEAEF7B4Eu, 0x4077475Fu, 0xB4C9655Du },
    },
    /* table[60] = G_2 + G_3 + G_4 + G_5 (affine) */
    {
        { 0x6C38B3DAu, 0x3C3D8C9Bu, 0x754433E3u, 0x80818302u, 0xE29E542Au, 0xFE68AB07u, 0xD12CBB2Cu, 0x81A25A61u },
        { 0x8F685647u, 0x559948A7u, 0x83A56574u, 0xE14EBCF6u, 0x7A77DB0Fu, 0x1A606632u, 0x0892CE93u, 0xF49D838Fu },
    },
    /* table[61] = G_0 + G_2 + G_3 + G_4 + G_5 (affine) */
    {
        { 0xFCF866B9u, 0xF3F4E3FEu, 0xE18B0AD5u, 0x152A0807u, 0x1B9B2E7Bu, 0x2EC4C706u, 0xDADD006Fu, 0x41D7E92Bu },
        { 0x1D4B6EF7u, 0xFF0A8A79u, 0xB2AA2F47u, 0x02344DFFu, 0x357A0681u, 0x1726D704u, 0xC1BC85F4u, 0x4CE6BB77u },
    },
    /* table[62] = G_1 + G_2 + G_3 + G_4 + G_5 (affine) */
    {
        { 0x8916A00Du, 0x651EBB86u, 0x001E908Du, 0xBA4D2DA9u, 0x1684FCB0u, 0x5F2B68E6u, 0x10AC6EDFu, 0xC3FF8D75u },
        { 0xF5C49A61u, 0x6997E3EAu, 0xB1A4DC68u, 0x8F4FF372u, 0xC95C2DB2u, 0xBEA7CE04u, 0x9D10F761u, 0x2ACCB4F4u },
    },
    /* table[63] = G_0 + G_1 + G_2 + G_3 + G_4 + G_5 (affine) */
    {
        { 0xAFCC2BEFu, 0xB9E437F4u, 0x3ADA2B53u, 0x4F1FB2D6u, 0xBB580C9Au, 0xE6C0E12Du, 0x33C7546Du, 0x25183734u },
        { 0xBFD92FB9u, 0xAB12D90Fu, 0xA185AE46u, 0x2CB9B9B3u, 0x9CE6F49Fu, 0x2A0C7A7Eu, 0xB48F21F2u, 0x531F307Fu },
    },
};

#endif /* SSF_EC_P256_COMB_TABLE_H6_INCLUDE */
