/* --------------------------------------------------------------------------------------------- */
/* Small System Framework                                                                        */
/*                                                                                               */
/* ssfec_p256_comb_table_h4.h                                                                  */
/* Precomputed Lim-Lee comb table for fixed-base P256 scalar multiplication.                  */
/*                                                                                               */
/* Layout: 16 entries x 2 coordinates (X, Y) x 8 limbs (32-bit, little-endian limb order).   */
/* h = 4 strips, d = 64 bits per strip. Entries are in AFFINE form (Z = 1 implicit).                */
/* Entry 0 is a sentinel; the comb runtime restores r from a saved copy when mask==0.            */
/*                                                                                               */
/* table[mask] = sum_{j: bit j of mask is set} G_j  where G_j = [2^(j*64)] G  for j in 0..3.    */
/*                                                                                               */
/* Auto-generated by tools/gen_comb.py -- do not edit by hand.                                    */
/*                                                                                               */
/* BSD-3-Clause License                                                                          */
/* Copyright 2026 Supurloop Software LLC                                                         */
/* --------------------------------------------------------------------------------------------- */
#ifndef SSF_EC_P256_COMB_TABLE_H4_INCLUDE
#define SSF_EC_P256_COMB_TABLE_H4_INCLUDE

static const SSFBNLimb_t _ssfECP256CombStorage[16][2][8] = {
    /* table[ 0] = O (identity sentinel; runtime restores r when mask==0) */
    {
        { 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u },
        { 0x00000001u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u },
    },
    /* table[ 1] = G_0 (affine) */
    {
        { 0xD898C296u, 0xF4A13945u, 0x2DEB33A0u, 0x77037D81u, 0x63A440F2u, 0xF8BCE6E5u, 0xE12C4247u, 0x6B17D1F2u },
        { 0x37BF51F5u, 0xCBB64068u, 0x6B315ECEu, 0x2BCE3357u, 0x7C0F9E16u, 0x8EE7EB4Au, 0xFE1A7F9Bu, 0x4FE342E2u },
    },
    /* table[ 2] = G_1 (affine) */
    {
        { 0x8E14DB63u, 0x90E75CB4u, 0xAD651F7Eu, 0x29493BAAu, 0x326E25DEu, 0x8492592Eu, 0x2811AAA5u, 0x0FA822BCu },
        { 0x5F462EE7u, 0xE4112454u, 0x50FE82F5u, 0x34B1A650u, 0xB3DF188Bu, 0x6F4AD4BCu, 0xF5DBA80Du, 0xBFF44AE8u },
    },
    /* table[ 3] = G_0 + G_1 (affine) */
    {
        { 0x097992AFu, 0x93391CE2u, 0x0D35F1FAu, 0xE96C98FDu, 0x95E02789u, 0xB257C0DEu, 0x89D6726Fu, 0x300A4BBCu },
        { 0xC08127A0u, 0xAA54A291u, 0xA9D806A5u, 0x5BB1EEADu, 0xFF1E3C6Fu, 0x7F1DDB25u, 0xD09B4644u, 0x72AAC7E0u },
    },
    /* table[ 4] = G_2 (affine) */
    {
        { 0xD789BD85u, 0x57C84FC9u, 0xC297EAC3u, 0xFC35FF7Du, 0x88C6766Eu, 0xFB982FD5u, 0xEEDB5E67u, 0x447D739Bu },
        { 0x72E25B32u, 0x0C7E33C9u, 0xA7FAE500u, 0x3D349B95u, 0x3A4AAFF7u, 0xE12E9D95u, 0x834131EEu, 0x2D4825ABu },
    },
    /* table[ 5] = G_0 + G_2 (affine) */
    {
        { 0x2A1D367Fu, 0x13949C93u, 0x1A0A11B7u, 0xEF7FBD2Bu, 0xB91DFC60u, 0xDDC6068Bu, 0x8A9C72FFu, 0xEF951932u },
        { 0x7376D8A8u, 0x196035A7u, 0x95CA1740u, 0x23183B08u, 0x022C219Cu, 0xC1EE9807u, 0x7DBB2C9Bu, 0x611E9FC3u },
    },
    /* table[ 6] = G_1 + G_2 (affine) */
    {
        { 0x0B57F4BCu, 0xCAE2B192u, 0xC6C9BC36u, 0x2936DF5Eu, 0xE11238BFu, 0x7DEA6482u, 0x7B51F5D8u, 0x55066379u },
        { 0x348A964Cu, 0x44FFE216u, 0xDBDEFBE1u, 0x9FB3D576u, 0x8D9D50E5u, 0x0AFA4001u, 0x8AECB851u, 0x15716484u },
    },
    /* table[ 7] = G_0 + G_1 + G_2 (affine) */
    {
        { 0xFC5CDE01u, 0xE48ECAFFu, 0x0D715F26u, 0x7CCD84E7u, 0xF43E4391u, 0xA2E8F483u, 0xB21141EAu, 0xEB5D7745u },
        { 0x731A3479u, 0xCAC917E2u, 0x2844B645u, 0x85F22CFEu, 0x58006CEEu, 0x0990E6A1u, 0xDBECC17Bu, 0xEAFD72EBu },
    },
    /* table[ 8] = G_3 (affine) */
    {
        { 0x313728BEu, 0x6CF20FFBu, 0xA3C6B94Au, 0x96439591u, 0x44315FC5u, 0x2736FF83u, 0xA7849276u, 0xA6D39677u },
        { 0xC357F5F4u, 0xF2BAB833u, 0x2284059Bu, 0x824A920Cu, 0x2D27ECDFu, 0x66B8BABDu, 0x9B0B8816u, 0x674F8474u },
    },
    /* table[ 9] = G_0 + G_3 (affine) */
    {
        { 0x677C8A3Eu, 0x2DF48C04u, 0x0203A56Bu, 0x74E02F08u, 0xB8C7FEDBu, 0x31855F7Du, 0x72C9DDADu, 0x4E769E76u },
        { 0xB824BBB0u, 0xA4C36165u, 0x3B9122A5u, 0xFB9AE16Fu, 0x06947281u, 0x1EC00572u, 0xDE830663u, 0x42B99082u },
    },
    /* table[10] = G_1 + G_3 (affine) */
    {
        { 0xDDA868B9u, 0x6EF95150u, 0x9C0CE131u, 0xD1F89E79u, 0x08A1C478u, 0x7FDC1CA0u, 0x1C6CE04Du, 0x78878EF6u },
        { 0x1FE0D976u, 0x9C62B912u, 0xBDE08D4Fu, 0x6ACE570Eu, 0x12309DEFu, 0xDE53142Cu, 0x7B72C321u, 0xB6CB3F5Du },
    },
    /* table[11] = G_0 + G_1 + G_3 (affine) */
    {
        { 0xC31A3573u, 0x7F991ED2u, 0xD54FB496u, 0x5B82DD5Bu, 0x812FFCAEu, 0x595C5220u, 0x716B1287u, 0x0C88BC4Du },
        { 0x5F48ACA8u, 0x3A57BF63u, 0xDF2564F3u, 0x7C8181F4u, 0x9C04E6AAu, 0x18D1B5B3u, 0xF3901DC6u, 0xDD5DDEA3u },
    },
    /* table[12] = G_2 + G_3 (affine) */
    {
        { 0x3E72AD0Cu, 0xE96A79FBu, 0x42BA792Fu, 0x43A0A28Cu, 0x083E49F3u, 0xEFE0A423u, 0x6B317466u, 0x68F344AFu },
        { 0x3FB24D4Au, 0xCDFE17DBu, 0x71F5C626u, 0x668BFC22u, 0x24D67FF3u, 0x604ED93Cu, 0xF8540A20u, 0x31B9C405u },
    },
    /* table[13] = G_0 + G_2 + G_3 (affine) */
    {
        { 0xA2582E7Fu, 0xD36B4789u, 0x4EC39C28u, 0x0D1A1014u, 0xEDBAD7A0u, 0x663C62C3u, 0x6F461DB9u, 0x4052BF4Bu },
        { 0x188D25EBu, 0x235A27C3u, 0x99BFCC5Bu, 0xE724F339u, 0x71D70CC8u, 0x862BE6BDu, 0x90B0FC61u, 0xFECF4D51u },
    },
    /* table[14] = G_1 + G_2 + G_3 (affine) */
    {
        { 0xA1D4CFACu, 0x74346C10u, 0x8526A7A4u, 0xAFDF5CC0u, 0xF62BFF7Au, 0x123202A8u, 0xC802E41Au, 0x1EDDBAE2u },
        { 0xD603F844u, 0x8FA0AF2Du, 0x4C701917u, 0x36E06B7Eu, 0x73DB33A0u, 0x0C45F452u, 0x560EBCFCu, 0x43104D86u },
    },
    /* table[15] = G_0 + G_1 + G_2 + G_3 (affine) */
    {
        { 0x0D1D78E5u, 0x9615B511u, 0x25C4744Bu, 0x66B0DE32u, 0x6AAF363Au, 0x0A4A46FBu, 0x84F7A21Cu, 0xB48E26B4u },
        { 0x21A01B2Du, 0x06EBB0F6u, 0x8B7B0F98u, 0xC004E404u, 0xFED6F668u, 0x64131BCDu, 0x4D4D3DABu, 0xFAC01540u },
    },
};

#endif /* SSF_EC_P256_COMB_TABLE_H4_INCLUDE */
