#!/usr/bin/env python3
"""Generate C header from a Wycheproof X25519 JSON test vector file.

Wycheproof X25519 vectors encode keys as raw 32-byte hex strings (no SPKI). SSF's
SSFX25519ComputeSecret takes raw 32-byte arrays, so the codegen is a direct passthrough
once the JSON is parsed.

Usage:
    python3 tools/gen_wycheproof_x25519.py <input.json> <out.h>

Example:
    python3 tools/gen_wycheproof_x25519.py \
        tools/wycheproof_data/x25519_test.json \
        _crypto/wycheproof_x25519.h
"""
import json
import sys


def hex_array(data: bytes) -> str:
    if not data:
        return "0u"
    return ", ".join(f"0x{b:02X}u" for b in data)


def emit(in_path: str, out_path: str) -> None:
    with open(in_path) as f:
        d = json.load(f)

    # X25519 always has a single testGroup (curve25519).
    assert len(d["testGroups"]) == 1, "expected single X25519 testGroup"
    g = d["testGroups"][0]

    out = []
    out.append("/* --------------------------------------------------------------------------------------------- */")
    out.append("/* Small System Framework                                                                        */")
    out.append("/*                                                                                               */")
    out.append("/* wycheproof_x25519.h                                                                           */")
    out.append("/* Wycheproof X25519 test vectors.                                                               */")
    out.append("/*                                                                                               */")
    out.append("/* Auto-generated by tools/gen_wycheproof_x25519.py from upstream Wycheproof testvectors_v1.     */")
    out.append("/* Keys are raw 32-byte u-coordinates / scalars (no DER wrapping).                                */")
    out.append("/*                                                                                               */")
    out.append("/* Source: https://github.com/google/wycheproof (testvectors_v1/)                                */")
    out.append("/*                                                                                               */")
    out.append(f"/* Total test cases: {d['numberOfTests']}                                                                         */")
    out.append("/*                                                                                               */")
    out.append("/* BSD-3-Clause License                                                                          */")
    out.append("/* Copyright 2026 Supurloop Software LLC                                                         */")
    out.append("/* --------------------------------------------------------------------------------------------- */")
    out.append("#ifndef SSF_WYCHEPROOF_X25519_H_INCLUDE")
    out.append("#define SSF_WYCHEPROOF_X25519_H_INCLUDE")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("#include <stdbool.h>")
    out.append("")

    descriptors = []
    for t in g["tests"]:
        tcid = t["tcId"]
        pub = bytes.fromhex(t["public"])
        priv = bytes.fromhex(t["private"])
        shared = bytes.fromhex(t["shared"])
        result = t["result"]

        # X25519 is strictly 32-byte keys / shared. Skip if any is malformed-sized; emit raw and
        # let SSF reject — but for X25519 there shouldn't be any.
        out.append(
            f"static const uint8_t _wp_X25519_pub_{tcid:04d}[{max(1, len(pub))}] = "
            f"{{ {hex_array(pub)} }};"
        )
        out.append(
            f"static const uint8_t _wp_X25519_priv_{tcid:04d}[{max(1, len(priv))}] = "
            f"{{ {hex_array(priv)} }};"
        )
        out.append(
            f"static const uint8_t _wp_X25519_shared_{tcid:04d}[{max(1, len(shared))}] = "
            f"{{ {hex_array(shared)} }};"
        )
        descriptors.append((tcid, len(pub), len(priv), len(shared), result))

    out.append("")
    out.append("typedef struct")
    out.append("{")
    out.append("    const uint8_t *pubKey;")
    out.append("    uint16_t       pubKeyLen;")
    out.append("    const uint8_t *privKey;")
    out.append("    uint16_t       privKeyLen;")
    out.append("    const uint8_t *shared;")
    out.append("    uint16_t       sharedLen;")
    out.append("    uint16_t       tcId;")
    out.append("    /* expectedValid: SSFX25519ComputeSecret should succeed AND output == shared.    */")
    out.append("    bool           expectedValid;")
    out.append("    /* acceptable: Wycheproof allows either accept-or-reject (don't count toward     */")
    out.append("    /* mismatch either way).                                                          */")
    out.append("    bool           acceptable;")
    out.append("} _SSFWycheproofX25519Test_t;")
    out.append("")
    out.append("static const _SSFWycheproofX25519Test_t _wp_X25519_tests[] = {")
    for tcid, pl, kl, sl, result in descriptors:
        if result == "valid":
            exp_valid, acceptable = "true", "false"
        elif result == "invalid":
            exp_valid, acceptable = "false", "false"
        else:  # acceptable
            exp_valid, acceptable = "true", "true"
        out.append(
            f"    {{ _wp_X25519_pub_{tcid:04d}, {pl}u, "
            f"_wp_X25519_priv_{tcid:04d}, {kl}u, "
            f"_wp_X25519_shared_{tcid:04d}, {sl}u, "
            f"{tcid}u, {exp_valid}, {acceptable} }},"
        )
    out.append("};")
    out.append("")
    out.append("#define SSF_WYCHEPROOF_X25519_NTESTS "
               "((sizeof(_wp_X25519_tests))/(sizeof(_wp_X25519_tests[0])))")
    out.append("")
    out.append("#endif /* SSF_WYCHEPROOF_X25519_H_INCLUDE */")
    out.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(out))
    n_valid = sum(1 for d in descriptors if d[4] == "valid")
    n_invalid = sum(1 for d in descriptors if d[4] == "invalid")
    n_acceptable = sum(1 for d in descriptors if d[4] == "acceptable")
    print(f"wrote {out_path}: {len(descriptors)} test cases "
          f"(valid={n_valid}, invalid={n_invalid}, acceptable={n_acceptable})")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    emit(sys.argv[1], sys.argv[2])
