#!/usr/bin/env python3
"""Generate Lim-Lee comb tables for P-256 and P-384, h=4/5/6.

Emits header files matching the existing layout in _crypto/ssfec_p{256,384}_comb_table_h{H}.h.
The h=4 outputs are designed to byte-match the existing tables as a generator sanity check.
"""
import sys

# NIST P-256
P256 = dict(
    name="P256",
    p=0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF,
    a=-3,
    b=0x5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B,
    Gx=0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296,
    Gy=0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5,
    n=0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551,
    nbits=256, limbs=8,
)

# NIST P-384
P384 = dict(
    name="P384",
    p=0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFF0000000000000000FFFFFFFF,
    a=-3,
    b=0xB3312FA7E23EE7E4988E056BE3F82D19181D9C6EFE8141120314088F5013875AC656398D8A2ED19D2A85C8EDD3EC2AEF,
    Gx=0xAA87CA22BE8B05378EB1C71EF320AD746E1D3B628BA79B9859F741E082542A385502F25DBF55296C3A545E3872760AB7,
    Gy=0x3617DE4A96262C6F5D9E98BF9292DC29F8F41DBD289A147CE9DA3113B5F0B8C00A60B1CE1D7E819D7A431D7C90EA0E5F,
    n=0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7634D81F4372DDF581A0DB248B0A77AECEC196ACCC52973,
    nbits=384, limbs=12,
)


def modinv(a, m):
    return pow(a, -1, m)


def is_inf(P):
    return P is None


def neg(P, p):
    if is_inf(P):
        return None
    return (P[0], (-P[1]) % p)


def add(P, Q, curve):
    p, a = curve['p'], curve['a'] % curve['p']
    if is_inf(P):
        return Q
    if is_inf(Q):
        return P
    x1, y1 = P; x2, y2 = Q
    if x1 == x2:
        if (y1 + y2) % p == 0:
            return None
        # Double
        s = ((3 * x1 * x1 + a) * modinv(2 * y1 % p, p)) % p
    else:
        s = ((y2 - y1) * modinv((x2 - x1) % p, p)) % p
    x3 = (s * s - x1 - x2) % p
    y3 = (s * (x1 - x3) - y1) % p
    return (x3, y3)


def scalar_mul(k, P, curve):
    R = None
    Q = P
    while k > 0:
        if k & 1:
            R = add(R, Q, curve)
        Q = add(Q, Q, curve)
        k >>= 1
    return R


def to_limbs(x, n_limbs):
    out = []
    for _ in range(n_limbs):
        out.append(x & 0xFFFFFFFF)
        x >>= 32
    return out


def fmt_limbs(limbs):
    return "{ " + ", ".join(f"0x{l:08X}u" for l in limbs) + " }"


def gen_table(curve, h):
    n = curve['nbits']
    d = (n + h - 1) // h
    G = (curve['Gx'], curve['Gy'])
    # G_j = [2^(j*d)] G  for j = 0..h-1
    Gs = []
    Gj = G
    Gs.append(Gj)
    for j in range(1, h):
        # Multiply Gj by 2^d
        for _ in range(d):
            Gj = add(Gj, Gj, curve)
        Gs.append(Gj)
    # table[mask] = sum_{j: bit j of mask set} Gs[j]
    table = []
    for mask in range(1 << h):
        if mask == 0:
            # Identity sentinel: encode as (0, 1) per the comb runtime convention.
            table.append((0, 1))
            continue
        acc = None
        for j in range(h):
            if mask & (1 << j):
                acc = add(acc, Gs[j], curve)
        assert acc is not None
        table.append(acc)
    return table, d


def emit(curve, h):
    name = curve['name']
    L = curve['limbs']
    n = curve['nbits']
    table, d = gen_table(curve, h)
    NTABLE = 1 << h

    g = []
    g.append("/* --------------------------------------------------------------------------------------------- */")
    g.append("/* Small System Framework                                                                        */")
    g.append("/*                                                                                               */")
    g.append(f"/* ssfec_{name.lower()}_comb_table_h{h}.h                                                                  */")
    g.append(f"/* Precomputed Lim-Lee comb table for fixed-base {name} scalar multiplication.                  */")
    g.append("/*                                                                                               */")
    g.append(f"/* Layout: {NTABLE} entries x 2 coordinates (X, Y) x {L} limbs (32-bit, little-endian limb order).{' ' * (4 - len(str(L)))}*/")
    g.append(f"/* h = {h} strips, d = {d} bits per strip. Entries are in AFFINE form (Z = 1 implicit).{' ' * (10)}      */")
    g.append("/* Entry 0 is a sentinel; the comb runtime restores r from a saved copy when mask==0.            */")
    g.append("/*                                                                                               */")
    g.append(f"/* table[mask] = sum_{{j: bit j of mask is set}} G_j  where G_j = [2^(j*{d})] G  for j in 0..{h-1}.    */")
    g.append("/*                                                                                               */")
    g.append("/* Auto-generated by tools/gen_comb.py — do not edit by hand.                                     */")
    g.append("/*                                                                                               */")
    g.append("/* BSD-3-Clause License                                                                          */")
    g.append("/* Copyright 2026 Supurloop Software LLC                                                         */")
    g.append("/* --------------------------------------------------------------------------------------------- */")
    g.append(f"#ifndef SSF_EC_{name}_COMB_TABLE_H{h}_INCLUDE")
    g.append(f"#define SSF_EC_{name}_COMB_TABLE_H{h}_INCLUDE")
    g.append("")
    g.append(f"static const SSFBNLimb_t _ssfEC{name}CombStorage[{NTABLE}][2][{L}] = {{")
    # Comments per entry
    def label(mask):
        if mask == 0:
            return "O (identity sentinel; runtime restores r when mask==0)"
        terms = [f"G_{j}" for j in range(h) if mask & (1 << j)]
        return " + ".join(terms) + " (affine)"
    for mask in range(NTABLE):
        x, y = table[mask]
        g.append(f"    /* table[{mask:2d}] = {label(mask)} */")
        g.append("    {")
        g.append(f"        {fmt_limbs(to_limbs(x, L))},")
        g.append(f"        {fmt_limbs(to_limbs(y, L))},")
        g.append("    },")
    g.append("};")
    g.append("")
    g.append(f"#endif /* SSF_EC_{name}_COMB_TABLE_H{h}_INCLUDE */")
    return "\n".join(g) + "\n"


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "/Users/jhiggins/ssf/_crypto"
    for curve in (P256, P384):
        for h in (4, 5, 6):
            path = f"{out_dir}/ssfec_{curve['name'].lower()}_comb_table_h{h}.h"
            content = emit(curve, h)
            with open(path, "w") as f:
                f.write(content)
            print(f"wrote {path}  (h={h}, d={(curve['nbits']+h-1)//h}, entries={1<<h})")


if __name__ == "__main__":
    main()
