#!/usr/bin/env python3
"""Generate C header from a Wycheproof Ed25519 JSON test vector file.

Wycheproof Ed25519 vectors group tests by public key — each testGroup carries one pubkey
(`publicKey.pk`) and a list of (msg, sig, result) tests. We flatten across groups so each
emitted descriptor row carries its own pubkey reference.

Usage:
    python3 tools/gen_wycheproof_ed25519.py <input.json> <out.h>
"""
import json
import sys


def hex_array(data: bytes) -> str:
    if not data:
        return "0u"
    return ", ".join(f"0x{b:02X}u" for b in data)


def emit(in_path: str, out_path: str) -> None:
    with open(in_path) as f:
        d = json.load(f)

    out = []
    out.append("/* --------------------------------------------------------------------------------------------- */")
    out.append("/* Small System Framework                                                                        */")
    out.append("/*                                                                                               */")
    out.append("/* wycheproof_ed25519.h                                                                          */")
    out.append("/* Wycheproof Ed25519 verify test vectors.                                                       */")
    out.append("/*                                                                                               */")
    out.append("/* Auto-generated by tools/gen_wycheproof_ed25519.py from upstream Wycheproof testvectors_v1.    */")
    out.append("/*                                                                                               */")
    out.append("/* Source: https://github.com/google/wycheproof (testvectors_v1/)                                */")
    out.append("/*                                                                                               */")
    out.append(f"/* Total test cases: {d['numberOfTests']}                                                                          */")
    out.append("/*                                                                                               */")
    out.append("/* BSD-3-Clause License                                                                          */")
    out.append("/* Copyright 2026 Supurloop Software LLC                                                         */")
    out.append("/* --------------------------------------------------------------------------------------------- */")
    out.append("#ifndef SSF_WYCHEPROOF_ED25519_H_INCLUDE")
    out.append("#define SSF_WYCHEPROOF_ED25519_H_INCLUDE")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("#include <stdbool.h>")
    out.append("")

    # Per-group pubkey constants (one per group).
    pub_names = {}
    for gi, g in enumerate(d["testGroups"]):
        pub = bytes.fromhex(g["publicKey"]["pk"])
        name = f"_wp_Ed25519_pub_g{gi:03d}"
        pub_names[gi] = name
        out.append(
            f"static const uint8_t {name}[{len(pub)}] = {{ {hex_array(pub)} }};"
        )
    out.append("")

    # Per-test msg + sig constants.
    descriptors = []
    for gi, g in enumerate(d["testGroups"]):
        for t in g["tests"]:
            tcid = t["tcId"]
            msg = bytes.fromhex(t["msg"])
            sig = bytes.fromhex(t["sig"])
            result = t["result"]
            msg_name = f"_wp_Ed25519_msg_{tcid:04d}"
            sig_name = f"_wp_Ed25519_sig_{tcid:04d}"
            out.append(
                f"static const uint8_t {msg_name}[{max(1, len(msg))}] = "
                f"{{ {hex_array(msg)} }};"
            )
            out.append(
                f"static const uint8_t {sig_name}[{max(1, len(sig))}] = "
                f"{{ {hex_array(sig)} }};"
            )
            descriptors.append((tcid, gi, len(msg), len(sig), result))

    out.append("")
    out.append("typedef struct")
    out.append("{")
    out.append("    const uint8_t *pubKey;")
    out.append("    const uint8_t *msg;")
    out.append("    uint16_t       msgLen;")
    out.append("    const uint8_t *sig;")
    out.append("    uint16_t       sigLen;")
    out.append("    uint16_t       tcId;")
    out.append("    /* expectedValid: SSFEd25519Verify should return true iff this is set.     */")
    out.append("    bool           expectedValid;")
    out.append("    /* acceptable: Wycheproof allows either accept-or-reject.                  */")
    out.append("    bool           acceptable;")
    out.append("} _SSFWycheproofEd25519Test_t;")
    out.append("")
    out.append("static const _SSFWycheproofEd25519Test_t _wp_Ed25519_tests[] = {")
    for tcid, gi, ml, sl, result in descriptors:
        if result == "valid":
            exp_valid, acceptable = "true", "false"
        elif result == "invalid":
            exp_valid, acceptable = "false", "false"
        else:
            exp_valid, acceptable = "true", "true"
        out.append(
            f"    {{ {pub_names[gi]}, "
            f"_wp_Ed25519_msg_{tcid:04d}, {ml}u, "
            f"_wp_Ed25519_sig_{tcid:04d}, {sl}u, "
            f"{tcid}u, {exp_valid}, {acceptable} }},"
        )
    out.append("};")
    out.append("")
    out.append("#define SSF_WYCHEPROOF_ED25519_NTESTS "
               "((sizeof(_wp_Ed25519_tests))/(sizeof(_wp_Ed25519_tests[0])))")
    out.append("")
    out.append("#endif /* SSF_WYCHEPROOF_ED25519_H_INCLUDE */")
    out.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(out))
    n_valid = sum(1 for d_ in descriptors if d_[4] == "valid")
    n_invalid = sum(1 for d_ in descriptors if d_[4] == "invalid")
    n_accept = sum(1 for d_ in descriptors if d_[4] == "acceptable")
    print(f"wrote {out_path}: {len(descriptors)} test cases "
          f"(valid={n_valid}, invalid={n_invalid}, acceptable={n_accept})")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    emit(sys.argv[1], sys.argv[2])
