#!/usr/bin/env python3
"""Generate C header from a Wycheproof ECDH JSON test vector file.

Wycheproof ECDH vectors encode peer public keys as DER SubjectPublicKeyInfo (SPKI). SSF's
SSFECDHComputeSecret expects raw SEC1 uncompressed bytes. We strip the SPKI wrapper at
codegen time and emit raw SEC1 bytes; tests where the SPKI is malformed and we cannot
extract a SEC1 payload are marked with their original raw bytes and expectedValid=false
(SSF will reject the malformed pubkey at the PointDecode boundary).

Usage:
    python3 tools/gen_wycheproof_ecdh.py <input.json> <out.h> <curve_label> <token> <coord_bytes>

Example:
    python3 tools/gen_wycheproof_ecdh.py \
        tools/wycheproof_data/ecdh_secp256r1_test.json \
        _crypto/wycheproof_ecdh_p256.h P-256 P256 32
"""
import json
import sys


def hex_array(data: bytes) -> str:
    if not data:
        return "0u"
    return ", ".join(f"0x{b:02X}u" for b in data)


def strip_spki(spki: bytes, coord_bytes: int) -> bytes | None:
    """Extract raw SEC1 uncompressed pubKey bytes from a SubjectPublicKeyInfo DER blob.

    Returns the SEC1 bytes (1 + 2*coord_bytes), or None if the SPKI is malformed or
    doesn't contain an uncompressed point of the expected size.
    """
    expected_sec1_len = 1 + 2 * coord_bytes
    try:
        # SubjectPublicKeyInfo ::= SEQUENCE { algorithm AlgorithmIdentifier, subjectPublicKey BIT STRING }
        # Walk: 0x30 outer, then skip AlgorithmIdentifier (a SEQUENCE), then BIT STRING.
        pos = 0
        if spki[pos] != 0x30:
            return None
        pos += 1
        # Read length (short or long form).
        if spki[pos] < 0x80:
            outer_len = spki[pos]; pos += 1
        elif spki[pos] == 0x81:
            outer_len = spki[pos + 1]; pos += 2
        elif spki[pos] == 0x82:
            outer_len = (spki[pos + 1] << 8) | spki[pos + 2]; pos += 3
        else:
            return None
        if pos + outer_len != len(spki):
            return None
        # Skip AlgorithmIdentifier (inner SEQUENCE).
        if spki[pos] != 0x30:
            return None
        pos += 1
        if spki[pos] < 0x80:
            algo_len = spki[pos]; pos += 1
        elif spki[pos] == 0x81:
            algo_len = spki[pos + 1]; pos += 2
        else:
            return None
        pos += algo_len  # skip algorithm OID + parameters
        # BIT STRING.
        if pos >= len(spki) or spki[pos] != 0x03:
            return None
        pos += 1
        if spki[pos] < 0x80:
            bs_len = spki[pos]; pos += 1
        elif spki[pos] == 0x81:
            bs_len = spki[pos + 1]; pos += 2
        else:
            return None
        # First byte of BIT STRING value is the unused-bits count (must be 0 for SEC1).
        if spki[pos] != 0x00:
            return None
        pos += 1
        sec1 = spki[pos:pos + bs_len - 1]  # -1 for the unused-bits byte we consumed
        if len(sec1) != expected_sec1_len:
            return None
        if sec1[0] != 0x04:  # only uncompressed accepted
            return None
        return sec1
    except (IndexError, ValueError):
        return None


def emit(in_path: str, out_path: str, curve_label: str, token: str, coord_bytes: int) -> None:
    with open(in_path) as f:
        d = json.load(f)

    # Wycheproof ECDH has a single testGroup (curve-wide).
    assert len(d["testGroups"]) == 1, "expected single ECDH testGroup"
    g = d["testGroups"][0]

    out = []
    out.append("/* --------------------------------------------------------------------------------------------- */")
    out.append("/* Small System Framework                                                                        */")
    out.append("/*                                                                                               */")
    out.append(f"/* wycheproof_ecdh_{token.lower()}.h                                                                */")
    out.append(f"/* Wycheproof ECDH test vectors for {curve_label}.                                                       */")
    out.append("/*                                                                                               */")
    out.append("/* Auto-generated by tools/gen_wycheproof_ecdh.py from upstream Wycheproof testvectors_v1.        */")
    out.append("/* Public keys are stripped from SubjectPublicKeyInfo DER to raw SEC1 uncompressed at codegen.    */")
    out.append("/* Tests where the SPKI was malformed retain the original bytes and expectedValid=false.         */")
    out.append("/*                                                                                               */")
    out.append("/* Source: https://github.com/google/wycheproof (testvectors_v1/)                                */")
    out.append("/*                                                                                               */")
    out.append(f"/* Total test cases: {d['numberOfTests']}                                                                         */")
    out.append("/*                                                                                               */")
    out.append("/* BSD-3-Clause License                                                                          */")
    out.append("/* Copyright 2026 Supurloop Software LLC                                                         */")
    out.append("/* --------------------------------------------------------------------------------------------- */")
    out.append(f"#ifndef SSF_WYCHEPROOF_ECDH_{token.upper()}_H_INCLUDE")
    out.append(f"#define SSF_WYCHEPROOF_ECDH_{token.upper()}_H_INCLUDE")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("#include <stdbool.h>")
    out.append("")

    # Per-test arrays.
    descriptors = []
    for t in g["tests"]:
        tcid = t["tcId"]
        spki = bytes.fromhex(t["public"])
        priv = bytes.fromhex(t["private"])
        shared = bytes.fromhex(t["shared"])
        result = t["result"]

        # Normalize privKey to exactly coord_bytes — SSFECDHComputeSecret's API requires this.
        # Wycheproof commonly emits leading-zero-padded 33-byte (P-256) / 49-byte (P-384) keys.
        # Strip leading zeros if present; pad with zeros if shorter. If after stripping the value
        # still exceeds coord_bytes (impossible for in-range privKeys but Wycheproof has malformed
        # cases), force-truncate to coord_bytes — SSF will then reject as invalid privKey range.
        if len(priv) > coord_bytes:
            stripped = priv.lstrip(b"\x00")
            # Re-pad to exactly coord_bytes.
            if len(stripped) <= coord_bytes:
                priv = b"\x00" * (coord_bytes - len(stripped)) + stripped
            else:
                # Genuinely too large — keep the low coord_bytes (will fail privKey validation).
                priv = stripped[-coord_bytes:]
        elif len(priv) < coord_bytes:
            priv = b"\x00" * (coord_bytes - len(priv)) + priv

        sec1 = strip_spki(spki, coord_bytes)
        if sec1 is None:
            # Could not parse SPKI (malformed). Emit original bytes; SSF will reject them.
            pub_bytes = spki
            spki_failed = True
        else:
            pub_bytes = sec1
            spki_failed = False

        out.append(
            f"static const uint8_t _wp_{token}_pub_{tcid:04d}[{max(1, len(pub_bytes))}] = "
            f"{{ {hex_array(pub_bytes)} }};"
        )
        out.append(
            f"static const uint8_t _wp_{token}_priv_{tcid:04d}[{max(1, len(priv))}] = "
            f"{{ {hex_array(priv)} }};"
        )
        out.append(
            f"static const uint8_t _wp_{token}_shared_{tcid:04d}[{max(1, len(shared))}] = "
            f"{{ {hex_array(shared)} }};"
        )
        descriptors.append((tcid, len(pub_bytes), len(priv), len(shared), result, spki_failed))

    out.append("")
    out.append("typedef struct")
    out.append("{")
    out.append("    const uint8_t *pubKey;")
    out.append("    uint16_t       pubKeyLen;")
    out.append("    const uint8_t *privKey;")
    out.append("    uint16_t       privKeyLen;")
    out.append("    const uint8_t *shared;")
    out.append("    uint16_t       sharedLen;")
    out.append("    uint16_t       tcId;")
    out.append("    /* expectedValid: true if SSFECDHComputeSecret should succeed AND output == shared. */")
    out.append("    bool           expectedValid;")
    out.append("    /* spkiFailed: SPKI couldn't be parsed at codegen; SSF must reject the raw bytes.  */")
    out.append("    bool           spkiFailed;")
    out.append("    /* acceptable: Wycheproof says either accept-or-reject is OK (we treat as 'don't  */")
    out.append("    /* count toward mismatch either way'). */")
    out.append("    bool           acceptable;")
    out.append(f"}} _SSFWycheproofEcdh{token}Test_t;")
    out.append("")
    out.append(f"static const _SSFWycheproofEcdh{token}Test_t _wp_{token}_ecdh_tests[] = {{")
    for tcid, pl, kl, sl, result, spki_failed in descriptors:
        # "valid" -> expectedValid true
        # "invalid" -> expectedValid false
        # "acceptable" -> tracked separately; expectedValid set to whichever matches "valid path"
        if result == "valid":
            exp_valid, acceptable = "true", "false"
        elif result == "invalid":
            exp_valid, acceptable = "false", "false"
        else:  # acceptable
            exp_valid, acceptable = "true", "true"
        out.append(
            f"    {{ _wp_{token}_pub_{tcid:04d}, {pl}u, "
            f"_wp_{token}_priv_{tcid:04d}, {kl}u, "
            f"_wp_{token}_shared_{tcid:04d}, {sl}u, "
            f"{tcid}u, {exp_valid}, {'true' if spki_failed else 'false'}, {acceptable} }},"
        )
    out.append("};")
    out.append("")
    out.append(f"#define SSF_WYCHEPROOF_ECDH_{token.upper()}_NTESTS "
               f"((sizeof(_wp_{token}_ecdh_tests))/(sizeof(_wp_{token}_ecdh_tests[0])))")
    out.append("")
    out.append(f"#endif /* SSF_WYCHEPROOF_ECDH_{token.upper()}_H_INCLUDE */")
    out.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(out))
    n_spki_failed = sum(1 for d in descriptors if d[5])
    print(f"wrote {out_path}: {len(descriptors)} test cases, {n_spki_failed} with malformed SPKI")


if __name__ == "__main__":
    if len(sys.argv) != 6:
        print(__doc__)
        sys.exit(1)
    emit(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], int(sys.argv[5]))
