#!/usr/bin/env python3
"""Generate C header from a Wycheproof ECDSA verify JSON test vector file.

Reads a Wycheproof testvectors_v1 JSON file (e.g. ecdsa_secp256r1_sha256_test.json)
and emits a header `_crypto/wycheproof_ecdsa_<curve>.h` containing:
  - per-group pubkey byte arrays
  - per-test msg and sig byte arrays
  - one descriptor table tying them together

Usage:
    python3 tools/gen_wycheproof.py <input.json> <out.h> <curve_label> <token>

Example:
    python3 tools/gen_wycheproof.py \
        tools/wycheproof_data/ecdsa_secp256r1_sha256_test.json \
        _crypto/wycheproof_ecdsa_p256.h P-256 P256
"""
import json
import sys


def hex_array(data: bytes) -> str:
    if not data:
        return "0u"  # placeholder so the array has at least one element
    return ", ".join(f"0x{b:02X}u" for b in data)


def emit(in_path: str, out_path: str, curve_label: str, token: str) -> None:
    with open(in_path) as f:
        d = json.load(f)

    groups = d["testGroups"]
    out = []

    out.append("/* --------------------------------------------------------------------------------------------- */")
    out.append("/* Small System Framework                                                                        */")
    out.append("/*                                                                                               */")
    out.append(f"/* wycheproof_ecdsa_{token.lower()}.h                                                                */")
    out.append(f"/* Wycheproof ECDSA verify test vectors for {curve_label}.                                              */")
    out.append("/*                                                                                               */")
    out.append("/* Auto-generated by tools/gen_wycheproof.py from upstream Wycheproof testvectors_v1.            */")
    out.append("/* Do not edit by hand. Re-run the generator when Wycheproof updates.                            */")
    out.append("/*                                                                                               */")
    out.append("/* Source: https://github.com/google/wycheproof (testvectors_v1/)                                */")
    out.append("/*                                                                                               */")
    out.append(f"/* Total test cases: {d['numberOfTests']}                                                                          */")
    out.append("/*                                                                                               */")
    out.append("/* BSD-3-Clause License                                                                          */")
    out.append("/* Copyright 2026 Supurloop Software LLC                                                         */")
    out.append("/* --------------------------------------------------------------------------------------------- */")
    out.append(f"#ifndef SSF_WYCHEPROOF_ECDSA_{token.upper()}_H_INCLUDE")
    out.append(f"#define SSF_WYCHEPROOF_ECDSA_{token.upper()}_H_INCLUDE")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("#include <stdbool.h>")
    out.append("")

    # Per-group pubkey arrays.
    for gi, g in enumerate(groups):
        pk_hex = g["publicKey"]["uncompressed"]
        pk = bytes.fromhex(pk_hex)
        out.append(f"static const uint8_t _wp_{token}_pk_{gi:03d}[{max(1, len(pk))}] = {{ {hex_array(pk)} }};")

    out.append("")

    # Per-test msg and sig arrays + collect descriptors.
    descriptors = []
    for gi, g in enumerate(groups):
        pk_len = len(bytes.fromhex(g["publicKey"]["uncompressed"]))
        for t in g["tests"]:
            tcid = t["tcId"]
            msg = bytes.fromhex(t["msg"])
            sig = bytes.fromhex(t["sig"])
            out.append(
                f"static const uint8_t _wp_{token}_msg_{tcid:04d}[{max(1, len(msg))}] = "
                f"{{ {hex_array(msg)} }};"
            )
            out.append(
                f"static const uint8_t _wp_{token}_sig_{tcid:04d}[{max(1, len(sig))}] = "
                f"{{ {hex_array(sig)} }};"
            )
            descriptors.append((gi, tcid, pk_len, len(msg), len(sig), t["result"]))

    out.append("")

    # Test descriptor struct + table.
    out.append("typedef struct")
    out.append("{")
    out.append("    const uint8_t *pubKey;")
    out.append("    uint16_t       pubKeyLen;")
    out.append("    const uint8_t *msg;")
    out.append("    uint16_t       msgLen;")
    out.append("    const uint8_t *sig;")
    out.append("    uint16_t       sigLen;")
    out.append("    uint16_t       tcId;")
    out.append("    bool           expectedValid;")
    out.append(f"}} _SSFWycheproofEcdsa{token}Test_t;")
    out.append("")
    out.append(f"static const _SSFWycheproofEcdsa{token}Test_t _wp_{token}_tests[] = {{")
    for gi, tcid, pk_len, msg_len, sig_len, result in descriptors:
        # Treat "valid" as expected-true; everything else (incl. "invalid") as expected-false.
        # Wycheproof v1 for ECDSA-P-256 has only valid/invalid; older "acceptable" doesn't appear.
        exp = "true" if result == "valid" else "false"
        out.append(
            f"    {{ _wp_{token}_pk_{gi:03d}, {pk_len}u, "
            f"_wp_{token}_msg_{tcid:04d}, {msg_len}u, "
            f"_wp_{token}_sig_{tcid:04d}, {sig_len}u, "
            f"{tcid}u, {exp} }},"
        )
    out.append("};")
    out.append("")
    out.append(f"#define SSF_WYCHEPROOF_ECDSA_{token.upper()}_NTESTS "
               f"((sizeof(_wp_{token}_tests))/(sizeof(_wp_{token}_tests[0])))")
    out.append("")
    out.append(f"#endif /* SSF_WYCHEPROOF_ECDSA_{token.upper()}_H_INCLUDE */")
    out.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(out))

    print(f"wrote {out_path}: {len(descriptors)} test cases, {len(groups)} groups")


if __name__ == "__main__":
    if len(sys.argv) != 5:
        print(__doc__)
        sys.exit(1)
    emit(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
