#!/usr/bin/env python3
"""Generate a C header from the NIST CAVS AES KAT response (.rsp) files.

Reads tools/cavs_data/ECB{GFSbox,KeySbox,VarKey,VarTxt}{128,192,256}.rsp and
emits _crypto/cavs_aes_kat.h with one descriptor table per category x key-size,
each entry pairing a (key, plaintext, ciphertext) triple.

The CAVS framework validates AES-CTR by validating the underlying AES block
primitive. Running these KATs against SSFAES{128,192,256}BlockEncrypt covers
the structured-input edge cases (S-box, key-schedule walking-1s, plaintext
walking-1s) that random sweeps don't reliably hit.

Usage:
    python3 tools/gen_cavs_aes.py
"""
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "tools" / "cavs_data"
OUT_PATH = REPO_ROOT / "_crypto" / "cavs_aes_kat.h"

CATEGORIES = ["GFSbox", "KeySbox", "VarKey", "VarTxt"]
KEY_SIZES = [128, 192, 256]


def parse_rsp(path: Path):
    """Parse a CAVS .rsp file. Returns dict with 'ENCRYPT' and 'DECRYPT' lists
    of (count, key_hex, pt_hex, ct_hex) tuples."""
    sections = {"ENCRYPT": [], "DECRYPT": []}
    section = None
    cur = {}
    with open(path) as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if line == "[ENCRYPT]":
                section = "ENCRYPT"
                continue
            if line == "[DECRYPT]":
                section = "DECRYPT"
                continue
            m = re.match(r"^([A-Z]+)\s*=\s*(.+)$", line)
            if not m:
                continue
            tag, val = m.group(1), m.group(2)
            cur[tag] = val
            # ENCRYPT lists ciphertext last, DECRYPT lists plaintext last; flush
            # the record when we have all four fields regardless of the order
            # they appeared.
            if "KEY" in cur and "PLAINTEXT" in cur and "CIPHERTEXT" in cur:
                sections[section].append((
                    int(cur.get("COUNT", "0")),
                    cur["KEY"],
                    cur["PLAINTEXT"],
                    cur["CIPHERTEXT"],
                ))
                cur = {}
    return sections


def hex_array(hex_str: str) -> str:
    if not hex_str:
        return "0u"
    bs = bytes.fromhex(hex_str)
    return ", ".join(f"0x{b:02X}u" for b in bs)


def emit_header(all_vectors):
    out = []
    out.append("/* --------------------------------------------------------------------------------------------- */")
    out.append("/* Small System Framework                                                                        */")
    out.append("/*                                                                                               */")
    out.append("/* cavs_aes_kat.h                                                                                */")
    out.append("/* NIST CAVS AES Known-Answer Test vectors (ECB-mode, used to validate the AES block primitive  */")
    out.append("/* that AES-CTR / AES-GCM / AES-CCM build on).                                                   */")
    out.append("/*                                                                                               */")
    out.append("/* Auto-generated by tools/gen_cavs_aes.py from tools/cavs_data/ECB*.rsp.                        */")
    out.append("/* Do not edit by hand. Re-run the generator if the upstream vectors change.                     */")
    out.append("/*                                                                                               */")
    out.append("/* Source: https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/ */")
    out.append("/*         documents/aes/KAT_AES.zip (CAVS 11.1, dated 2011-04-22)                               */")
    out.append("/*                                                                                               */")
    out.append("/* Categories: GFSbox (S-box edges), KeySbox (key-schedule edges), VarKey (walking-1s key),     */")
    out.append("/*             VarTxt (walking-1s plaintext). Three key sizes (128/192/256). Both ENCRYPT and    */")
    out.append("/*             DECRYPT directions.                                                                */")
    out.append("/*                                                                                               */")
    out.append("/* BSD-3-Clause License                                                                          */")
    out.append("/* Copyright 2026 Supurloop Software LLC                                                         */")
    out.append("/* --------------------------------------------------------------------------------------------- */")
    out.append("#ifndef CAVS_AES_KAT_H_INCLUDE")
    out.append("#define CAVS_AES_KAT_H_INCLUDE")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("#include <stddef.h>")
    out.append("")
    out.append("typedef struct")
    out.append("{")
    out.append("    const uint8_t *key;")
    out.append("    uint8_t        keyLen;       /* 16 / 24 / 32 */")
    out.append("    const uint8_t *pt;           /* 16 bytes (one AES block) */")
    out.append("    const uint8_t *ct;           /* 16 bytes */")
    out.append("} SSFCAVSAESKAT_t;")
    out.append("")

    total = 0
    table_decls = []
    for cat in CATEGORIES:
        for keysize in KEY_SIZES:
            for direction in ("ENCRYPT", "DECRYPT"):
                tag = f"{cat}{keysize}_{direction}"
                vectors = all_vectors[(cat, keysize)][direction]
                if not vectors:
                    continue
                # Emit byte arrays for each vector
                for idx, (count, key, pt, ct) in enumerate(vectors):
                    out.append(f"static const uint8_t _kat_{tag}_{idx}_key[] = {{ {hex_array(key)} }};")
                    out.append(f"static const uint8_t _kat_{tag}_{idx}_pt[]  = {{ {hex_array(pt)} }};")
                    out.append(f"static const uint8_t _kat_{tag}_{idx}_ct[]  = {{ {hex_array(ct)} }};")
                # Emit descriptor table for this category/size/direction
                out.append("")
                out.append(f"static const SSFCAVSAESKAT_t _kat_{tag}[] = {{")
                for idx, (count, key, pt, ct) in enumerate(vectors):
                    keyLen = len(bytes.fromhex(key))
                    out.append(f"    {{ _kat_{tag}_{idx}_key, {keyLen}u, _kat_{tag}_{idx}_pt, _kat_{tag}_{idx}_ct }},")
                out.append("};")
                out.append(f"#define SSF_CAVS_AES_KAT_{tag.upper()}_N  ((sizeof(_kat_{tag}) / sizeof(_kat_{tag}[0])))")
                out.append("")
                table_decls.append(tag)
                total += len(vectors)

    out.append(f"#define SSF_CAVS_AES_KAT_TOTAL_N  ({total}u)")
    out.append("")
    out.append("#endif /* CAVS_AES_KAT_H_INCLUDE */")
    return "\n".join(out) + "\n"


def main():
    all_vectors = {}
    for cat in CATEGORIES:
        for keysize in KEY_SIZES:
            path = DATA_DIR / f"ECB{cat}{keysize}.rsp"
            if not path.exists():
                print(f"missing: {path}", file=sys.stderr)
                sys.exit(1)
            all_vectors[(cat, keysize)] = parse_rsp(path)

    OUT_PATH.write_text(emit_header(all_vectors))

    total = sum(
        len(v[d])
        for v in all_vectors.values()
        for d in ("ENCRYPT", "DECRYPT")
    )
    print(f"wrote {OUT_PATH} ({total} vectors)")


if __name__ == "__main__":
    main()
